import React, { createContext, useContext, useState, useEffect } from 'react';

const SettingsContext = createContext(null);

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
};

// Available themes
export const themes = {
  dark: {
    id: 'dark',
    name: 'Dark',
    description: 'Default dark theme',
    colors: {
      background: 'bg-black',
      text: 'text-white',
      accent: 'amber'
    }
  },
  light: {
    id: 'light',
    name: 'Light',
    description: 'Light mode theme',
    colors: {
      background: 'bg-white',
      text: 'text-gray-900',
      accent: 'amber'
    }
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep blue dark theme',
    colors: {
      background: 'bg-slate-950',
      text: 'text-white',
      accent: 'blue'
    }
  },
  cinema: {
    id: 'cinema',
    name: 'Cinema',
    description: 'Classic cinema red accent',
    colors: {
      background: 'bg-neutral-950',
      text: 'text-white',
      accent: 'red'
    }
  }
};

// Available languages
export const languages = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸'
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸'
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷'
  },
  de: {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪'
  },
  zh: {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    flag: '🇨🇳'
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵'
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷'
  },
  pt: {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    flag: '🇧🇷'
  }
};

// Translation strings
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.catalog': 'Catalog',
    'nav.people': 'People',
    'nav.contact': 'Contact',
    'nav.settings': 'Settings',
    'nav.profile': 'My Profile',
    'nav.watchlist': 'Watchlist',
    'nav.signOut': 'Sign Out',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account settings and preferences',
    'settings.profile': 'Profile',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.profileInfo': 'Profile Information',
    'settings.profilePicture': 'Profile Picture',
    'settings.clickToUpload': 'Click on the avatar to upload a new image',
    'settings.bannerImage': 'Banner Image',
    'settings.recommendedSize': 'Recommended size: 1500x500px',
    'settings.uploadBanner': 'Upload Banner',
    'settings.uploading': 'Uploading...',
    'settings.displayName': 'Display Name',
    'settings.displayNamePlaceholder': 'Your display name',
    'settings.bio': 'Bio',
    'settings.bioPlaceholder': 'Tell us about yourself...',
    'settings.accountInfo': 'Account Information',
    'settings.username': 'Username',
    'settings.usernameCannotChange': 'Username cannot be changed',
    'settings.email': 'Email',
    'settings.memberSince': 'Member Since',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.currentPasswordPlaceholder': 'Enter current password',
    'settings.newPassword': 'New Password',
    'settings.newPasswordPlaceholder': 'Enter new password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'settings.confirmPasswordPlaceholder': 'Confirm new password',
    'settings.updatePassword': 'Update Password',
    'settings.updating': 'Updating...',
    'settings.selectLanguage': 'Select your preferred language for the interface',
    'settings.languageAutoSave': 'Language changes are saved automatically',
    'settings.someContentOriginal': 'Some content may still appear in the original language.',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.seeAll': 'See all',
    'common.search': 'Search',
    'common.clear': 'Clear',
    'common.clearFilters': 'Clear Filters',
    'common.films': 'films',
    'common.or': 'OR',
    // Watchlist
    'watchlist.empty': 'Your watchlist is empty',
    'watchlist.emptyDescription': 'Save films to watch later by clicking the bookmark icon',
    'watchlist.browseFilms': 'Browse Films',
    'watchlist.savedFilms': 'films saved to watch later',
    'watchlist.savedFilm': 'film saved to watch later',
    'watchlist.removeConfirm': 'Remove from your watchlist?',
    'watchlist.removeError': 'Failed to remove from watchlist. Please try again.',
    'watchlist.remove': 'Remove from watchlist',
    // People page
    'people.discoverPeople': 'Discover People',
    'people.findConnect': 'Find and connect with film enthusiasts',
    'people.searchPlaceholder': 'Search by username or name...',
    'people.result': 'result',
    'people.results': 'results',
    'people.noUsersFound': 'No users found',
    'people.suggestedForYou': 'Suggested For You',
    'people.noSuggestions': 'No suggestions yet',
    'people.noSuggestionsDescription': 'Add some favorite films to get personalized recommendations',
    'people.followers': 'followers',
    'people.films': 'films',
    'people.loading': 'Loading...',
    'people.following': 'Following',
    'people.follow': 'Follow',
    // Search
    'search.placeholder': 'Search films, directors, moods...',
    'search.results': 'Results',
    'search.matches': 'matches',
    'search.noResults': 'No titles matched',
    'search.tryDifferent': 'Try a different search term',
    'search.recent': 'Recent',
    'search.trending': 'Trending on NEMA',
    // Home Page
    'home.independentCinema': 'Independent Cinema',
    'home.tagline': 'Discover storytelling beyond boundaries.',
    'home.subtitle': 'A curated collection of unique voices and perspectives in contemporary cinema.',
    'home.exploreFilms': 'Explore Films',
    'home.featuredFilm': 'Featured Film',
    'home.explore': 'Explore',
    'home.curatorsSelection': "Curator's Selection",
    'home.featured': 'Featured',
    'home.newReleases': 'New Releases',
    'home.topRated': 'Top Rated',
    'home.play': 'Play',
    'home.moreInfo': 'More Info',
    'home.supportCinema': 'Support Independent Cinema',
    'home.supportText': 'Join our community of filmmakers and film enthusiasts. Watch, share, and discover unique stories that define our time.',
    'home.joinCommunity': 'Join Our Community',
    'home.allRightsReserved': 'All rights reserved.',
    // Catalog Page
    'catalog.filmCollection': 'Film Collection',
    'catalog.title': 'Catalog',
    'catalog.subtitle': 'Browse the archive and discover your next favorite film.',
    'catalog.loadingMovies': 'Loading movies...',
    'catalog.loadingMore': 'Loading more films...',
    'catalog.showingAll': 'Showing all',
    'catalog.noFilms': 'No films found matching your criteria.',
    'catalog.category': 'Category',
    'catalog.year': 'Year',
    'catalog.language': 'Language',
    'catalog.sort': 'Sort',
    'catalog.filters': 'Filters',
    'catalog.newest': 'Newest',
    'catalog.oldest': 'Oldest',
    'catalog.aToZ': 'A-Z',
    // Login Page
    'login.title': 'Sign In',
    'login.emailOrUsername': 'Email or Username',
    'login.password': 'Password',
    'login.signingIn': 'SIGNING IN...',
    'login.signIn': 'SIGN IN',
    'login.noAccount': "Don't have an account?",
    'login.enterCredentials': 'Please enter your email/username and password',
    // Register Page
    'register.title': 'Create Account',
    'register.username': 'Username',
    'register.email': 'Email',
    'register.displayName': 'Display Name (optional)',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.creating': 'CREATING ACCOUNT...',
    'register.create': 'CREATE ACCOUNT',
    'register.hasAccount': 'Already have an account?',
    // Contact Page
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with our team',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    // About Page
    'about.title': 'About',
    'about.subtitle': 'Learn more about NEMA',
    // Profile Page
    'profile.title': 'Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.posts': 'Posts',
    // Video Player
    'video.play': 'Play',
    'video.pause': 'Pause',
    'video.mute': 'Mute',
    'video.unmute': 'Unmute',
    'video.fullscreen': 'Fullscreen',
    'video.exitFullscreen': 'Exit Fullscreen',
    'video.synopsis': 'Synopsis',
    'video.genre': 'Genre',
    'video.language': 'Language',
    'video.cast': 'Cast',
    'video.more': 'more',
    'video.relatedFilms': 'Related Films',
    'video.addToWatchlist': 'Add to Watchlist',
    'video.inWatchlist': 'In Watchlist',
    'video.addToFavorites': 'Add to Favorites',
    'video.inFavorites': 'In Favorites',
    'video.loading': 'Loading...',
    'video.loadingMovie': 'Loading movie...',
    'video.noVideo': 'No video available',
    'video.directedBy': 'Directed by',
    // Footer
    'footer.films': 'Films',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    // Reviews
    'reviews.title': 'Reviews',
    'reviews.average': 'average',
    'reviews.clickToRate': 'Click to rate',
    'reviews.nicknamePlaceholder': 'Nickname (optional)',
    'reviews.writeReview': 'Write a short review (optional)…',
    'reviews.submitReview': 'Submit Review',
    'reviews.updateReview': 'Update Review',
    'reviews.loading': 'Loading reviews…',
    'reviews.noReviews': 'No reviews yet.',
    'reviews.deleteConfirm': 'Are you sure you want to delete your review?',
    'reviews.deleteError': 'You can only delete your own reviews',
    'reviews.rateLimitError': 'Too many attempts. Please try again later.',
    'reviews.submitError': 'Failed to submit review. Please try again.',
    'reviews.deleteReviewError': 'Failed to delete review. Please try again.',
    // Comments
    'comments.title': 'Comments',
    'comments.nicknamePlaceholder': 'Nickname (optional)',
    'comments.addComment': 'Add a comment...',
    'comments.posting': 'Posting...',
    'comments.postComment': 'Post Comment',
    'comments.loading': 'Loading comments...',
    'comments.noComments': 'No comments yet. Be the first to comment!',
    'comments.delete': 'Delete',
    'comments.deleteConfirm': 'Are you sure you want to delete this comment?',
    'comments.deleteError': 'You can only delete your own comments',
    'comments.rateLimitError': 'Too many delete attempts. Please try again later.',
    'comments.postError': 'Failed to post comment',
    'comments.loadError': 'Failed to load comments',
    'comments.deleteCommentError': 'Failed to delete comment',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.catalog': 'Catálogo',
    'nav.people': 'Personas',
    'nav.contact': 'Contacto',
    'nav.settings': 'Configuración',
    'nav.profile': 'Mi Perfil',
    'nav.watchlist': 'Lista de seguimiento',
    'nav.signOut': 'Cerrar sesión',
    'nav.signIn': 'Iniciar sesión',
    'nav.signUp': 'Registrarse',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Administra la configuración y preferencias de tu cuenta',
    'settings.profile': 'Perfil',
    'settings.account': 'Cuenta',
    'settings.appearance': 'Apariencia',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.save': 'Guardar cambios',
    'settings.saving': 'Guardando...',
    'settings.profileInfo': 'Información del Perfil',
    'settings.profilePicture': 'Foto de Perfil',
    'settings.clickToUpload': 'Haz clic en el avatar para subir una nueva imagen',
    'settings.bannerImage': 'Imagen de Portada',
    'settings.recommendedSize': 'Tamaño recomendado: 1500x500px',
    'settings.uploadBanner': 'Subir Portada',
    'settings.uploading': 'Subiendo...',
    'settings.displayName': 'Nombre para Mostrar',
    'settings.displayNamePlaceholder': 'Tu nombre para mostrar',
    'settings.bio': 'Biografía',
    'settings.bioPlaceholder': 'Cuéntanos sobre ti...',
    'settings.accountInfo': 'Información de la Cuenta',
    'settings.username': 'Usuario',
    'settings.usernameCannotChange': 'El nombre de usuario no se puede cambiar',
    'settings.email': 'Correo',
    'settings.memberSince': 'Miembro desde',
    'settings.changePassword': 'Cambiar Contraseña',
    'settings.currentPassword': 'Contraseña Actual',
    'settings.currentPasswordPlaceholder': 'Ingresa la contraseña actual',
    'settings.newPassword': 'Nueva Contraseña',
    'settings.newPasswordPlaceholder': 'Ingresa la nueva contraseña',
    'settings.confirmNewPassword': 'Confirmar Nueva Contraseña',
    'settings.confirmPasswordPlaceholder': 'Confirma la nueva contraseña',
    'settings.updatePassword': 'Actualizar Contraseña',
    'settings.updating': 'Actualizando...',
    'settings.selectLanguage': 'Selecciona tu idioma preferido para la interfaz',
    'settings.languageAutoSave': 'Los cambios de idioma se guardan automáticamente',
    'settings.someContentOriginal': 'Algunos contenidos pueden seguir apareciendo en el idioma original.',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.seeAll': 'Ver todo',
    'common.search': 'Buscar',
    'common.clear': 'Limpiar',
    'common.clearFilters': 'Limpiar filtros',
    'common.films': 'películas',
    'watchlist.empty': 'Tu lista de seguimiento está vacía',
    'watchlist.emptyDescription': 'Guarda películas para ver más tarde haciendo clic en el icono de marcador',
    'watchlist.browseFilms': 'Explorar Películas',
    'watchlist.savedFilms': 'películas guardadas para ver más tarde',
    'watchlist.savedFilm': 'película guardada para ver más tarde',
    'watchlist.removeConfirm': '¿Eliminar de tu lista de seguimiento?',
    'watchlist.removeError': 'Error al eliminar de la lista. Por favor, inténtalo de nuevo.',
    'watchlist.remove': 'Eliminar de la lista',
    // People page
    'people.discoverPeople': 'Descubrir Personas',
    'people.findConnect': 'Encuentra y conecta con entusiastas del cine',
    'people.searchPlaceholder': 'Buscar por nombre de usuario o nombre...',
    'people.result': 'resultado',
    'people.results': 'resultados',
    'people.noUsersFound': 'No se encontraron usuarios',
    'people.suggestedForYou': 'Sugeridos Para Ti',
    'people.noSuggestions': 'Sin sugerencias aún',
    'people.noSuggestionsDescription': 'Agrega algunas películas favoritas para obtener recomendaciones personalizadas',
    'people.followers': 'seguidores',
    'people.films': 'películas',
    'people.loading': 'Cargando...',
    'people.following': 'Siguiendo',
    'people.follow': 'Seguir',
    'common.or': 'O',
    'search.placeholder': 'Buscar películas, directores, géneros...',
    'search.results': 'Resultados',
    'search.matches': 'coincidencias',
    'search.noResults': 'No se encontraron títulos para',
    'search.tryDifferent': 'Intenta con otro término de búsqueda',
    'search.recent': 'Recientes',
    'search.trending': 'Tendencias en NEMA',
    'home.independentCinema': 'Cine Independiente',
    'home.tagline': 'Descubre narrativas sin fronteras.',
    'home.subtitle': 'Una colección curada de voces y perspectivas únicas en el cine contemporáneo.',
    'home.exploreFilms': 'Explorar Películas',
    'home.featuredFilm': 'Película Destacada',
    'home.explore': 'Explorar',
    'home.curatorsSelection': 'Selección del Curador',
    'home.featured': 'Destacados',
    'home.newReleases': 'Nuevos Lanzamientos',
    'home.topRated': 'Mejor Valorados',
    'home.play': 'Reproducir',
    'home.moreInfo': 'Más Información',
    'home.supportCinema': 'Apoya el Cine Independiente',
    'home.supportText': 'Únete a nuestra comunidad de cineastas y entusiastas del cine. Mira, comparte y descubre historias únicas que definen nuestro tiempo.',
    'home.joinCommunity': 'Únete a Nuestra Comunidad',
    'home.allRightsReserved': 'Todos los derechos reservados.',
    'catalog.filmCollection': 'Colección de Películas',
    'catalog.title': 'Catálogo',
    'catalog.subtitle': 'Explora el archivo y descubre tu próxima película favorita.',
    'catalog.loadingMovies': 'Cargando películas...',
    'catalog.loadingMore': 'Cargando más películas...',
    'catalog.showingAll': 'Mostrando todas',
    'catalog.noFilms': 'No se encontraron películas con esos criterios.',
    'catalog.category': 'Categoría',
    'catalog.year': 'Año',
    'catalog.language': 'Idioma',
    'catalog.sort': 'Ordenar',
    'catalog.filters': 'Filtros',
    'catalog.newest': 'Más recientes',
    'catalog.oldest': 'Más antiguos',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Iniciar Sesión',
    'login.emailOrUsername': 'Correo o Usuario',
    'login.password': 'Contraseña',
    'login.signingIn': 'INICIANDO SESIÓN...',
    'login.signIn': 'INICIAR SESIÓN',
    'login.noAccount': '¿No tienes cuenta?',
    'login.enterCredentials': 'Por favor ingresa tu correo/usuario y contraseña',
    'register.title': 'Crear Cuenta',
    'register.username': 'Usuario',
    'register.email': 'Correo',
    'register.displayName': 'Nombre para mostrar (opcional)',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar Contraseña',
    'register.creating': 'CREANDO CUENTA...',
    'register.create': 'CREAR CUENTA',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'contact.title': 'Contacto',
    'contact.subtitle': 'Ponte en contacto con nuestro equipo',
    'contact.name': 'Nombre',
    'contact.email': 'Correo',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'about.title': 'Acerca de',
    'about.subtitle': 'Conoce más sobre NEMA',
    'profile.title': 'Perfil',
    'profile.editProfile': 'Editar Perfil',
    'profile.followers': 'Seguidores',
    'profile.following': 'Siguiendo',
    'profile.posts': 'Publicaciones',
    'video.play': 'Reproducir',
    'video.pause': 'Pausar',
    'video.mute': 'Silenciar',
    'video.unmute': 'Activar sonido',
    'video.fullscreen': 'Pantalla completa',
    'video.exitFullscreen': 'Salir de pantalla completa',
    'video.synopsis': 'Sinopsis',
    'video.genre': 'Género',
    'video.language': 'Idioma',
    'video.cast': 'Reparto',
    'video.more': 'más',
    'video.relatedFilms': 'Películas Relacionadas',
    'video.addToWatchlist': 'Añadir a Lista',
    'video.inWatchlist': 'En Lista',
    'video.addToFavorites': 'Añadir a Favoritos',
    'video.inFavorites': 'En Favoritos',
    'video.loading': 'Cargando...',
    'video.loadingMovie': 'Cargando película...',
    'video.noVideo': 'No hay video disponible',
    'video.directedBy': 'Dirigida por',
    'footer.films': 'Películas',
    'footer.about': 'Acerca de',
    'footer.contact': 'Contacto',
    // Reviews
    'reviews.title': 'Reseñas',
    'reviews.average': 'promedio',
    'reviews.clickToRate': 'Haz clic para calificar',
    'reviews.nicknamePlaceholder': 'Apodo (opcional)',
    'reviews.writeReview': 'Escribe una reseña corta (opcional)…',
    'reviews.submitReview': 'Enviar Reseña',
    'reviews.updateReview': 'Actualizar Reseña',
    'reviews.loading': 'Cargando reseñas…',
    'reviews.noReviews': 'Aún no hay reseñas.',
    'reviews.deleteConfirm': '¿Estás seguro de que quieres eliminar tu reseña?',
    'reviews.deleteError': 'Solo puedes eliminar tus propias reseñas',
    'reviews.rateLimitError': 'Demasiados intentos. Por favor intenta más tarde.',
    'reviews.submitError': 'Error al enviar la reseña. Por favor intenta de nuevo.',
    'reviews.deleteReviewError': 'Error al eliminar la reseña. Por favor intenta de nuevo.',
    // Comments
    'comments.title': 'Comentarios',
    'comments.nicknamePlaceholder': 'Apodo (opcional)',
    'comments.addComment': 'Añadir un comentario...',
    'comments.posting': 'Publicando...',
    'comments.postComment': 'Publicar Comentario',
    'comments.loading': 'Cargando comentarios...',
    'comments.noComments': '¡Aún no hay comentarios. Sé el primero en comentar!',
    'comments.delete': 'Eliminar',
    'comments.deleteConfirm': '¿Estás seguro de que quieres eliminar este comentario?',
    'comments.deleteError': 'Solo puedes eliminar tus propios comentarios',
    'comments.rateLimitError': 'Demasiados intentos de eliminación. Por favor intenta más tarde.',
    'comments.postError': 'Error al publicar el comentario',
    'comments.loadError': 'Error al cargar los comentarios',
    'comments.deleteCommentError': 'Error al eliminar el comentario',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.catalog': 'Catalogue',
    'nav.people': 'Personnes',
    'nav.contact': 'Contact',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Mon Profil',
    'nav.watchlist': 'Liste de suivi',
    'nav.signOut': 'Déconnexion',
    'nav.signIn': 'Connexion',
    'nav.signUp': "S'inscrire",
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez les paramètres et préférences de votre compte',
    'settings.profile': 'Profil',
    'settings.account': 'Compte',
    'settings.appearance': 'Apparence',
    'settings.language': 'Langue',
    'settings.theme': 'Thème',
    'settings.save': 'Enregistrer',
    'settings.saving': 'Enregistrement...',
    'settings.profileInfo': 'Informations du Profil',
    'settings.profilePicture': 'Photo de Profil',
    'settings.clickToUpload': 'Cliquez sur l\'avatar pour télécharger une nouvelle image',
    'settings.bannerImage': 'Image de Bannière',
    'settings.recommendedSize': 'Taille recommandée: 1500x500px',
    'settings.uploadBanner': 'Télécharger la Bannière',
    'settings.uploading': 'Téléchargement...',
    'settings.displayName': 'Nom d\'Affichage',
    'settings.displayNamePlaceholder': 'Votre nom d\'affichage',
    'settings.bio': 'Biographie',
    'settings.bioPlaceholder': 'Parlez-nous de vous...',
    'settings.accountInfo': 'Informations du Compte',
    'settings.username': 'Nom d\'utilisateur',
    'settings.usernameCannotChange': 'Le nom d\'utilisateur ne peut pas être modifié',
    'settings.email': 'Email',
    'settings.memberSince': 'Membre depuis',
    'settings.changePassword': 'Changer le Mot de Passe',
    'settings.currentPassword': 'Mot de Passe Actuel',
    'settings.currentPasswordPlaceholder': 'Entrez le mot de passe actuel',
    'settings.newPassword': 'Nouveau Mot de Passe',
    'settings.newPasswordPlaceholder': 'Entrez le nouveau mot de passe',
    'settings.confirmNewPassword': 'Confirmer le Nouveau Mot de Passe',
    'settings.confirmPasswordPlaceholder': 'Confirmez le nouveau mot de passe',
    'settings.updatePassword': 'Mettre à Jour le Mot de Passe',
    'settings.updating': 'Mise à jour...',
    'settings.selectLanguage': 'Sélectionnez votre langue préférée pour l\'interface',
    'settings.languageAutoSave': 'Les changements de langue sont enregistrés automatiquement',
    'settings.someContentOriginal': 'Certains contenus peuvent encore apparaître dans la langue d\'origine.',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.seeAll': 'Voir tout',
    'common.search': 'Rechercher',
    'common.clear': 'Effacer',
    'common.clearFilters': 'Effacer les filtres',
    'common.films': 'films',
    'common.or': 'OU',
    'watchlist.empty': 'Votre liste est vide',
    'watchlist.emptyDescription': 'Enregistrez des films à regarder plus tard en cliquant sur l\'icône de signet',
    'watchlist.browseFilms': 'Parcourir les Films',
    'watchlist.savedFilms': 'films enregistrés à regarder plus tard',
    'watchlist.savedFilm': 'film enregistré à regarder plus tard',
    'watchlist.removeConfirm': 'Retirer de votre liste?',
    'watchlist.removeError': 'Échec de la suppression. Veuillez réessayer.',
    'watchlist.remove': 'Retirer de la liste',
    // People page
    'people.discoverPeople': 'Découvrir des Personnes',
    'people.findConnect': 'Trouvez et connectez-vous avec des passionnés de cinéma',
    'people.searchPlaceholder': 'Rechercher par nom d\'utilisateur ou nom...',
    'people.result': 'résultat',
    'people.results': 'résultats',
    'people.noUsersFound': 'Aucun utilisateur trouvé',
    'people.suggestedForYou': 'Suggestions Pour Vous',
    'people.noSuggestions': 'Pas encore de suggestions',
    'people.noSuggestionsDescription': 'Ajoutez des films favoris pour obtenir des recommandations personnalisées',
    'people.followers': 'abonnés',
    'people.films': 'films',
    'people.loading': 'Chargement...',
    'people.following': 'Abonné',
    'people.follow': 'Suivre',
    'search.placeholder': 'Rechercher films, réalisateurs, ambiances...',
    'search.results': 'Résultats',
    'search.matches': 'correspondances',
    'search.noResults': 'Aucun titre trouvé pour',
    'search.tryDifferent': 'Essayez un autre terme de recherche',
    'search.recent': 'Récents',
    'search.trending': 'Tendances sur NEMA',
    'home.independentCinema': 'Cinéma Indépendant',
    'home.tagline': 'Découvrez des récits sans frontières.',
    'home.subtitle': 'Une collection de voix et perspectives uniques dans le cinéma contemporain.',
    'home.exploreFilms': 'Explorer les Films',
    'home.featuredFilm': 'Film en Vedette',
    'home.explore': 'Explorer',
    'home.curatorsSelection': 'Sélection du Curateur',
    'home.featured': 'En Vedette',
    'home.newReleases': 'Nouvelles Sorties',
    'home.topRated': 'Les Mieux Notés',
    'home.play': 'Lecture',
    'home.moreInfo': 'Plus d\'Infos',
    'home.supportCinema': 'Soutenez le Cinéma Indépendant',
    'home.supportText': 'Rejoignez notre communauté de cinéastes et passionnés. Regardez, partagez et découvrez des histoires uniques qui définissent notre époque.',
    'home.joinCommunity': 'Rejoindre Notre Communauté',
    'home.allRightsReserved': 'Tous droits réservés.',
    'catalog.filmCollection': 'Collection de Films',
    'catalog.title': 'Catalogue',
    'catalog.subtitle': 'Parcourez les archives et découvrez votre prochain film préféré.',
    'catalog.loadingMovies': 'Chargement des films...',
    'catalog.loadingMore': 'Chargement de plus de films...',
    'catalog.showingAll': 'Affichage de tous les',
    'catalog.noFilms': 'Aucun film trouvé correspondant à vos critères.',
    'catalog.category': 'Catégorie',
    'catalog.year': 'Année',
    'catalog.language': 'Langue',
    'catalog.sort': 'Trier',
    'catalog.filters': 'Filtres',
    'catalog.newest': 'Plus récents',
    'catalog.oldest': 'Plus anciens',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Connexion',
    'login.emailOrUsername': 'Email ou Nom d\'utilisateur',
    'login.password': 'Mot de passe',
    'login.signingIn': 'CONNEXION...',
    'login.signIn': 'SE CONNECTER',
    'login.noAccount': 'Pas de compte?',
    'login.enterCredentials': 'Veuillez entrer votre email/nom d\'utilisateur et mot de passe',
    'register.title': 'Créer un Compte',
    'register.username': 'Nom d\'utilisateur',
    'register.email': 'Email',
    'register.displayName': 'Nom d\'affichage (facultatif)',
    'register.password': 'Mot de passe',
    'register.confirmPassword': 'Confirmer le mot de passe',
    'register.creating': 'CRÉATION DU COMPTE...',
    'register.create': 'CRÉER UN COMPTE',
    'register.hasAccount': 'Déjà un compte?',
    'contact.title': 'Contact',
    'contact.subtitle': 'Contactez notre équipe',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le Message',
    'contact.sending': 'Envoi...',
    'about.title': 'À propos',
    'about.subtitle': 'En savoir plus sur NEMA',
    'profile.title': 'Profil',
    'profile.editProfile': 'Modifier le Profil',
    'profile.followers': 'Abonnés',
    'profile.following': 'Abonnements',
    'profile.posts': 'Publications',
    'video.play': 'Lecture',
    'video.pause': 'Pause',
    'video.mute': 'Couper le son',
    'video.unmute': 'Activer le son',
    'video.fullscreen': 'Plein écran',
    'video.exitFullscreen': 'Quitter le plein écran',
    'video.synopsis': 'Synopsis',
    'video.genre': 'Genre',
    'video.language': 'Langue',
    'video.cast': 'Distribution',
    'video.more': 'de plus',
    'video.relatedFilms': 'Films Similaires',
    'video.addToWatchlist': 'Ajouter à la liste',
    'video.inWatchlist': 'Dans la liste',
    'video.addToFavorites': 'Ajouter aux favoris',
    'video.inFavorites': 'Dans les favoris',
    'video.loading': 'Chargement...',
    'video.loadingMovie': 'Chargement du film...',
    'video.noVideo': 'Aucune vidéo disponible',
    'video.directedBy': 'Réalisé par',
    'footer.films': 'Films',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    // Reviews
    'reviews.title': 'Critiques',
    'reviews.average': 'moyenne',
    'reviews.clickToRate': 'Cliquez pour noter',
    'reviews.nicknamePlaceholder': 'Pseudo (optionnel)',
    'reviews.writeReview': 'Écrivez une courte critique (optionnel)…',
    'reviews.submitReview': 'Soumettre la Critique',
    'reviews.updateReview': 'Mettre à jour la Critique',
    'reviews.loading': 'Chargement des critiques…',
    'reviews.noReviews': 'Pas encore de critiques.',
    'reviews.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer votre critique?',
    'reviews.deleteError': 'Vous ne pouvez supprimer que vos propres critiques',
    'reviews.rateLimitError': 'Trop de tentatives. Veuillez réessayer plus tard.',
    'reviews.submitError': 'Échec de l\'envoi de la critique. Veuillez réessayer.',
    'reviews.deleteReviewError': 'Échec de la suppression de la critique. Veuillez réessayer.',
    // Comments
    'comments.title': 'Commentaires',
    'comments.nicknamePlaceholder': 'Pseudo (optionnel)',
    'comments.addComment': 'Ajouter un commentaire...',
    'comments.posting': 'Publication...',
    'comments.postComment': 'Publier le Commentaire',
    'comments.loading': 'Chargement des commentaires...',
    'comments.noComments': 'Pas encore de commentaires. Soyez le premier à commenter!',
    'comments.delete': 'Supprimer',
    'comments.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce commentaire?',
    'comments.deleteError': 'Vous ne pouvez supprimer que vos propres commentaires',
    'comments.rateLimitError': 'Trop de tentatives de suppression. Veuillez réessayer plus tard.',
    'comments.postError': 'Échec de la publication du commentaire',
    'comments.loadError': 'Échec du chargement des commentaires',
    'comments.deleteCommentError': 'Échec de la suppression du commentaire',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.catalog': 'Katalog',
    'nav.people': 'Personen',
    'nav.contact': 'Kontakt',
    'nav.settings': 'Einstellungen',
    'nav.profile': 'Mein Profil',
    'nav.watchlist': 'Merkliste',
    'nav.signOut': 'Abmelden',
    'nav.signIn': 'Anmelden',
    'nav.signUp': 'Registrieren',
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Verwalten Sie Ihre Kontoeinstellungen und Präferenzen',
    'settings.profile': 'Profil',
    'settings.account': 'Konto',
    'settings.appearance': 'Erscheinungsbild',
    'settings.language': 'Sprache',
    'settings.theme': 'Thema',
    'settings.save': 'Änderungen speichern',
    'settings.saving': 'Speichern...',
    'settings.profileInfo': 'Profilinformationen',
    'settings.profilePicture': 'Profilbild',
    'settings.clickToUpload': 'Klicken Sie auf den Avatar, um ein neues Bild hochzuladen',
    'settings.bannerImage': 'Bannerbild',
    'settings.recommendedSize': 'Empfohlene Größe: 1500x500px',
    'settings.uploadBanner': 'Banner Hochladen',
    'settings.uploading': 'Hochladen...',
    'settings.displayName': 'Anzeigename',
    'settings.displayNamePlaceholder': 'Ihr Anzeigename',
    'settings.bio': 'Biografie',
    'settings.bioPlaceholder': 'Erzählen Sie uns von sich...',
    'settings.accountInfo': 'Kontoinformationen',
    'settings.username': 'Benutzername',
    'settings.usernameCannotChange': 'Der Benutzername kann nicht geändert werden',
    'settings.email': 'E-Mail',
    'settings.memberSince': 'Mitglied seit',
    'settings.changePassword': 'Passwort Ändern',
    'settings.currentPassword': 'Aktuelles Passwort',
    'settings.currentPasswordPlaceholder': 'Aktuelles Passwort eingeben',
    'settings.newPassword': 'Neues Passwort',
    'settings.newPasswordPlaceholder': 'Neues Passwort eingeben',
    'settings.confirmNewPassword': 'Neues Passwort Bestätigen',
    'settings.confirmPasswordPlaceholder': 'Neues Passwort bestätigen',
    'settings.updatePassword': 'Passwort Aktualisieren',
    'settings.updating': 'Aktualisieren...',
    'settings.selectLanguage': 'Wählen Sie Ihre bevorzugte Sprache für die Benutzeroberfläche',
    'settings.languageAutoSave': 'Sprachänderungen werden automatisch gespeichert',
    'settings.someContentOriginal': 'Einige Inhalte können noch in der Originalsprache erscheinen.',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.seeAll': 'Alle anzeigen',
    'common.search': 'Suchen',
    'common.clear': 'Löschen',
    'common.clearFilters': 'Filter löschen',
    'common.films': 'Filme',
    'common.or': 'ODER',
    'watchlist.empty': 'Ihre Merkliste ist leer',
    'watchlist.emptyDescription': 'Speichern Sie Filme zum späteren Ansehen, indem Sie auf das Lesezeichen-Symbol klicken',
    'watchlist.browseFilms': 'Filme durchsuchen',
    'watchlist.savedFilms': 'Filme zum späteren Ansehen gespeichert',
    'watchlist.savedFilm': 'Film zum späteren Ansehen gespeichert',
    'watchlist.removeConfirm': 'Von Ihrer Merkliste entfernen?',
    'watchlist.removeError': 'Fehler beim Entfernen. Bitte versuchen Sie es erneut.',
    'watchlist.remove': 'Von der Liste entfernen',
    // People page
    'people.discoverPeople': 'Leute Entdecken',
    'people.findConnect': 'Finden und verbinden Sie sich mit Filmbegeisterten',
    'people.searchPlaceholder': 'Nach Benutzername oder Name suchen...',
    'people.result': 'Ergebnis',
    'people.results': 'Ergebnisse',
    'people.noUsersFound': 'Keine Benutzer gefunden',
    'people.suggestedForYou': 'Vorschläge Für Sie',
    'people.noSuggestions': 'Noch keine Vorschläge',
    'people.noSuggestionsDescription': 'Fügen Sie Lieblingsfilme hinzu, um personalisierte Empfehlungen zu erhalten',
    'people.followers': 'Follower',
    'people.films': 'Filme',
    'people.loading': 'Laden...',
    'people.following': 'Folgst du',
    'people.follow': 'Folgen',
    'search.placeholder': 'Filme, Regisseure, Stimmungen suchen...',
    'search.results': 'Ergebnisse',
    'search.matches': 'Treffer',
    'search.noResults': 'Keine Titel gefunden für',
    'search.tryDifferent': 'Versuchen Sie einen anderen Suchbegriff',
    'search.recent': 'Zuletzt gesucht',
    'search.trending': 'Beliebt auf NEMA',
    'home.independentCinema': 'Unabhängiges Kino',
    'home.tagline': 'Entdecken Sie Geschichten ohne Grenzen.',
    'home.subtitle': 'Eine kuratierte Sammlung einzigartiger Stimmen und Perspektiven im zeitgenössischen Kino.',
    'home.exploreFilms': 'Filme Entdecken',
    'home.featuredFilm': 'Ausgewählter Film',
    'home.explore': 'Entdecken',
    'home.curatorsSelection': 'Kurator-Auswahl',
    'home.featured': 'Ausgewählt',
    'home.newReleases': 'Neuerscheinungen',
    'home.topRated': 'Bestbewertet',
    'home.play': 'Abspielen',
    'home.moreInfo': 'Mehr Infos',
    'home.supportCinema': 'Unterstützen Sie Unabhängiges Kino',
    'home.supportText': 'Treten Sie unserer Gemeinschaft von Filmemachern und Filmliebhabern bei. Schauen, teilen und entdecken Sie einzigartige Geschichten, die unsere Zeit definieren.',
    'home.joinCommunity': 'Unserer Gemeinschaft Beitreten',
    'home.allRightsReserved': 'Alle Rechte vorbehalten.',
    'catalog.filmCollection': 'Filmsammlung',
    'catalog.title': 'Katalog',
    'catalog.subtitle': 'Durchsuchen Sie das Archiv und entdecken Sie Ihren nächsten Lieblingsfilm.',
    'catalog.loadingMovies': 'Filme werden geladen...',
    'catalog.loadingMore': 'Weitere Filme werden geladen...',
    'catalog.showingAll': 'Zeige alle',
    'catalog.noFilms': 'Keine Filme gefunden, die Ihren Kriterien entsprechen.',
    'catalog.category': 'Kategorie',
    'catalog.year': 'Jahr',
    'catalog.language': 'Sprache',
    'catalog.sort': 'Sortieren',
    'catalog.filters': 'Filter',
    'catalog.newest': 'Neueste',
    'catalog.oldest': 'Älteste',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Anmelden',
    'login.emailOrUsername': 'E-Mail oder Benutzername',
    'login.password': 'Passwort',
    'login.signingIn': 'ANMELDEN...',
    'login.signIn': 'ANMELDEN',
    'login.noAccount': 'Noch kein Konto?',
    'login.enterCredentials': 'Bitte geben Sie Ihre E-Mail/Benutzername und Passwort ein',
    'register.title': 'Konto Erstellen',
    'register.username': 'Benutzername',
    'register.email': 'E-Mail',
    'register.displayName': 'Anzeigename (optional)',
    'register.password': 'Passwort',
    'register.confirmPassword': 'Passwort bestätigen',
    'register.creating': 'KONTO WIRD ERSTELLT...',
    'register.create': 'KONTO ERSTELLEN',
    'register.hasAccount': 'Bereits ein Konto?',
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Kontaktieren Sie unser Team',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht Senden',
    'contact.sending': 'Senden...',
    'about.title': 'Über uns',
    'about.subtitle': 'Erfahren Sie mehr über NEMA',
    'profile.title': 'Profil',
    'profile.editProfile': 'Profil Bearbeiten',
    'profile.followers': 'Follower',
    'profile.following': 'Folge ich',
    'profile.posts': 'Beiträge',
    'video.play': 'Abspielen',
    'video.pause': 'Pause',
    'video.mute': 'Stumm',
    'video.unmute': 'Ton an',
    'video.fullscreen': 'Vollbild',
    'video.exitFullscreen': 'Vollbild beenden',
    'video.synopsis': 'Handlung',
    'video.genre': 'Genre',
    'video.language': 'Sprache',
    'video.cast': 'Besetzung',
    'video.more': 'weitere',
    'video.relatedFilms': 'Ähnliche Filme',
    'video.addToWatchlist': 'Zur Merkliste',
    'video.inWatchlist': 'Auf Merkliste',
    'video.addToFavorites': 'Zu Favoriten',
    'video.inFavorites': 'In Favoriten',
    'video.loading': 'Laden...',
    'video.loadingMovie': 'Film wird geladen...',
    'video.noVideo': 'Kein Video verfügbar',
    'video.directedBy': 'Regie',
    'footer.films': 'Filme',
    'footer.about': 'Über uns',
    'footer.contact': 'Kontakt',
    // Reviews
    'reviews.title': 'Bewertungen',
    'reviews.average': 'Durchschnitt',
    'reviews.clickToRate': 'Klicken zum Bewerten',
    'reviews.nicknamePlaceholder': 'Spitzname (optional)',
    'reviews.writeReview': 'Schreiben Sie eine kurze Bewertung (optional)…',
    'reviews.submitReview': 'Bewertung Abgeben',
    'reviews.updateReview': 'Bewertung Aktualisieren',
    'reviews.loading': 'Bewertungen werden geladen…',
    'reviews.noReviews': 'Noch keine Bewertungen.',
    'reviews.deleteConfirm': 'Sind Sie sicher, dass Sie Ihre Bewertung löschen möchten?',
    'reviews.deleteError': 'Sie können nur Ihre eigenen Bewertungen löschen',
    'reviews.rateLimitError': 'Zu viele Versuche. Bitte versuchen Sie es später erneut.',
    'reviews.submitError': 'Bewertung konnte nicht gesendet werden. Bitte versuchen Sie es erneut.',
    'reviews.deleteReviewError': 'Bewertung konnte nicht gelöscht werden. Bitte versuchen Sie es erneut.',
    // Comments
    'comments.title': 'Kommentare',
    'comments.nicknamePlaceholder': 'Spitzname (optional)',
    'comments.addComment': 'Einen Kommentar hinzufügen...',
    'comments.posting': 'Wird gepostet...',
    'comments.postComment': 'Kommentar Posten',
    'comments.loading': 'Kommentare werden geladen...',
    'comments.noComments': 'Noch keine Kommentare. Seien Sie der Erste!',
    'comments.delete': 'Löschen',
    'comments.deleteConfirm': 'Sind Sie sicher, dass Sie diesen Kommentar löschen möchten?',
    'comments.deleteError': 'Sie können nur Ihre eigenen Kommentare löschen',
    'comments.rateLimitError': 'Zu viele Löschversuche. Bitte versuchen Sie es später erneut.',
    'comments.postError': 'Kommentar konnte nicht gepostet werden',
    'comments.loadError': 'Kommentare konnten nicht geladen werden',
    'comments.deleteCommentError': 'Kommentar konnte nicht gelöscht werden',
  },
  zh: {
    'nav.home': '首页',
    'nav.about': '关于',
    'nav.catalog': '目录',
    'nav.people': '用户',
    'nav.contact': '联系',
    'nav.settings': '设置',
    'nav.profile': '我的资料',
    'nav.watchlist': '观看列表',
    'nav.signOut': '退出',
    'nav.signIn': '登录',
    'nav.signUp': '注册',
    'settings.title': '设置',
    'settings.subtitle': '管理您的账户设置和偏好',
    'settings.profile': '个人资料',
    'settings.account': '账户',
    'settings.appearance': '外观',
    'settings.language': '语言',
    'settings.theme': '主题',
    'settings.save': '保存更改',
    'settings.saving': '保存中...',
    'settings.profileInfo': '个人资料信息',
    'settings.profilePicture': '头像',
    'settings.clickToUpload': '点击头像上传新图片',
    'settings.bannerImage': '横幅图片',
    'settings.recommendedSize': '推荐尺寸：1500x500像素',
    'settings.uploadBanner': '上传横幅',
    'settings.uploading': '上传中...',
    'settings.displayName': '显示名称',
    'settings.displayNamePlaceholder': '您的显示名称',
    'settings.bio': '个人简介',
    'settings.bioPlaceholder': '介绍一下自己...',
    'settings.accountInfo': '账户信息',
    'settings.username': '用户名',
    'settings.usernameCannotChange': '用户名不可更改',
    'settings.email': '邮箱',
    'settings.memberSince': '注册时间',
    'settings.changePassword': '修改密码',
    'settings.currentPassword': '当前密码',
    'settings.currentPasswordPlaceholder': '输入当前密码',
    'settings.newPassword': '新密码',
    'settings.newPasswordPlaceholder': '输入新密码',
    'settings.confirmNewPassword': '确认新密码',
    'settings.confirmPasswordPlaceholder': '确认新密码',
    'settings.updatePassword': '更新密码',
    'settings.updating': '更新中...',
    'settings.selectLanguage': '选择您偏好的界面语言',
    'settings.languageAutoSave': '语言更改会自动保存',
    'settings.someContentOriginal': '部分内容可能仍以原始语言显示。',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.seeAll': '查看全部',
    'common.search': '搜索',
    'common.clear': '清除',
    'common.clearFilters': '清除筛选',
    'common.films': '部电影',
    'common.or': '或',
    'watchlist.empty': '您的观看列表为空',
    'watchlist.emptyDescription': '点击书签图标保存稍后观看的电影',
    'watchlist.browseFilms': '浏览电影',
    'watchlist.savedFilms': '部电影已保存稍后观看',
    'watchlist.savedFilm': '部电影已保存稍后观看',
    'watchlist.removeConfirm': '从您的观看列表中移除？',
    'watchlist.removeError': '移除失败，请重试。',
    'watchlist.remove': '从列表中移除',
    // People page
    'people.discoverPeople': '发现用户',
    'people.findConnect': '寻找并与电影爱好者建立联系',
    'people.searchPlaceholder': '按用户名或姓名搜索...',
    'people.result': '个结果',
    'people.results': '个结果',
    'people.noUsersFound': '未找到用户',
    'people.suggestedForYou': '为您推荐',
    'people.noSuggestions': '暂无推荐',
    'people.noSuggestionsDescription': '添加一些喜欢的电影以获得个性化推荐',
    'people.followers': '位关注者',
    'people.films': '部电影',
    'people.loading': '加载中...',
    'people.following': '已关注',
    'people.follow': '关注',
    'search.placeholder': '搜索电影、导演、风格...',
    'search.results': '结果',
    'search.matches': '个匹配',
    'search.noResults': '未找到相关标题',
    'search.tryDifferent': '请尝试其他搜索词',
    'search.recent': '最近搜索',
    'search.trending': 'NEMA热门',
    'home.independentCinema': '独立电影',
    'home.tagline': '发现无边界的故事。',
    'home.subtitle': '当代电影中独特声音和视角的精选合集。',
    'home.exploreFilms': '探索电影',
    'home.featuredFilm': '精选电影',
    'home.explore': '探索',
    'home.curatorsSelection': '策展人精选',
    'home.featured': '精选',
    'home.newReleases': '新片上映',
    'home.topRated': '最高评分',
    'home.play': '播放',
    'home.moreInfo': '更多信息',
    'home.supportCinema': '支持独立电影',
    'home.supportText': '加入我们的电影制作人和电影爱好者社区。观看、分享和发现定义我们时代的独特故事。',
    'home.joinCommunity': '加入我们的社区',
    'home.allRightsReserved': '版权所有。',
    'catalog.filmCollection': '电影合集',
    'catalog.title': '目录',
    'catalog.subtitle': '浏览档案，发现您的下一部最爱电影。',
    'catalog.loadingMovies': '正在加载电影...',
    'catalog.loadingMore': '正在加载更多电影...',
    'catalog.showingAll': '显示全部',
    'catalog.noFilms': '未找到符合条件的电影。',
    'catalog.category': '类别',
    'catalog.year': '年份',
    'catalog.language': '语言',
    'catalog.sort': '排序',
    'catalog.filters': '筛选',
    'catalog.newest': '最新',
    'catalog.oldest': '最早',
    'catalog.aToZ': 'A-Z',
    'login.title': '登录',
    'login.emailOrUsername': '邮箱或用户名',
    'login.password': '密码',
    'login.signingIn': '登录中...',
    'login.signIn': '登录',
    'login.noAccount': '还没有账户？',
    'login.enterCredentials': '请输入您的邮箱/用户名和密码',
    'register.title': '创建账户',
    'register.username': '用户名',
    'register.email': '邮箱',
    'register.displayName': '显示名称（可选）',
    'register.password': '密码',
    'register.confirmPassword': '确认密码',
    'register.creating': '创建账户中...',
    'register.create': '创建账户',
    'register.hasAccount': '已有账户？',
    'contact.title': '联系',
    'contact.subtitle': '与我们的团队联系',
    'contact.name': '姓名',
    'contact.email': '邮箱',
    'contact.message': '消息',
    'contact.send': '发送消息',
    'contact.sending': '发送中...',
    'about.title': '关于',
    'about.subtitle': '了解更多关于NEMA',
    'profile.title': '个人资料',
    'profile.editProfile': '编辑资料',
    'profile.followers': '粉丝',
    'profile.following': '关注',
    'profile.posts': '帖子',
    'video.play': '播放',
    'video.pause': '暂停',
    'video.mute': '静音',
    'video.unmute': '取消静音',
    'video.fullscreen': '全屏',
    'video.exitFullscreen': '退出全屏',
    'video.synopsis': '剧情简介',
    'video.genre': '类型',
    'video.language': '语言',
    'video.cast': '演员阵容',
    'video.more': '更多',
    'video.relatedFilms': '相关电影',
    'video.addToWatchlist': '添加到列表',
    'video.inWatchlist': '已在列表',
    'video.addToFavorites': '添加到收藏',
    'video.inFavorites': '已收藏',
    'video.loading': '加载中...',
    'video.loadingMovie': '加载电影中...',
    'video.noVideo': '暂无视频',
    'video.directedBy': '导演',
    'footer.films': '电影',
    'footer.about': '关于',
    'footer.contact': '联系',
    // Reviews
    'reviews.title': '评论',
    'reviews.average': '平均',
    'reviews.clickToRate': '点击评分',
    'reviews.nicknamePlaceholder': '昵称（可选）',
    'reviews.writeReview': '写一段简短的评论（可选）…',
    'reviews.submitReview': '提交评论',
    'reviews.updateReview': '更新评论',
    'reviews.loading': '正在加载评论…',
    'reviews.noReviews': '暂无评论。',
    'reviews.deleteConfirm': '确定要删除您的评论吗？',
    'reviews.deleteError': '您只能删除自己的评论',
    'reviews.rateLimitError': '尝试次数过多。请稍后再试。',
    'reviews.submitError': '提交评论失败。请重试。',
    'reviews.deleteReviewError': '删除评论失败。请重试。',
    // Comments
    'comments.title': '留言',
    'comments.nicknamePlaceholder': '昵称（可选）',
    'comments.addComment': '添加留言...',
    'comments.posting': '发布中...',
    'comments.postComment': '发表留言',
    'comments.loading': '正在加载留言...',
    'comments.noComments': '暂无留言。成为第一个留言的人！',
    'comments.delete': '删除',
    'comments.deleteConfirm': '确定要删除这条留言吗？',
    'comments.deleteError': '您只能删除自己的留言',
    'comments.rateLimitError': '删除尝试次数过多。请稍后再试。',
    'comments.postError': '发布留言失败',
    'comments.loadError': '加载留言失败',
    'comments.deleteCommentError': '删除留言失败',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.about': '概要',
    'nav.catalog': 'カタログ',
    'nav.people': 'ユーザー',
    'nav.contact': '連絡先',
    'nav.settings': '設定',
    'nav.profile': 'マイプロフィール',
    'nav.watchlist': 'ウォッチリスト',
    'nav.signOut': 'ログアウト',
    'nav.signIn': 'ログイン',
    'nav.signUp': '新規登録',
    'settings.title': '設定',
    'settings.subtitle': 'アカウント設定と環境設定を管理',
    'settings.profile': 'プロフィール',
    'settings.account': 'アカウント',
    'settings.appearance': '外観',
    'settings.language': '言語',
    'settings.theme': 'テーマ',
    'settings.save': '変更を保存',
    'settings.saving': '保存中...',
    'settings.profileInfo': 'プロフィール情報',
    'settings.profilePicture': 'プロフィール写真',
    'settings.clickToUpload': 'アバターをクリックして新しい画像をアップロード',
    'settings.bannerImage': 'バナー画像',
    'settings.recommendedSize': '推奨サイズ：1500x500px',
    'settings.uploadBanner': 'バナーをアップロード',
    'settings.uploading': 'アップロード中...',
    'settings.displayName': '表示名',
    'settings.displayNamePlaceholder': 'あなたの表示名',
    'settings.bio': '自己紹介',
    'settings.bioPlaceholder': '自己紹介を書いてください...',
    'settings.accountInfo': 'アカウント情報',
    'settings.username': 'ユーザー名',
    'settings.usernameCannotChange': 'ユーザー名は変更できません',
    'settings.email': 'メール',
    'settings.memberSince': '登録日',
    'settings.changePassword': 'パスワードを変更',
    'settings.currentPassword': '現在のパスワード',
    'settings.currentPasswordPlaceholder': '現在のパスワードを入力',
    'settings.newPassword': '新しいパスワード',
    'settings.newPasswordPlaceholder': '新しいパスワードを入力',
    'settings.confirmNewPassword': '新しいパスワードを確認',
    'settings.confirmPasswordPlaceholder': '新しいパスワードを確認',
    'settings.updatePassword': 'パスワードを更新',
    'settings.updating': '更新中...',
    'settings.selectLanguage': 'インターフェースの言語を選択してください',
    'settings.languageAutoSave': '言語の変更は自動的に保存されます',
    'settings.someContentOriginal': '一部のコンテンツは元の言語で表示される場合があります。',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.seeAll': 'すべて見る',
    'common.search': '検索',
    'common.clear': 'クリア',
    'common.clearFilters': 'フィルターをクリア',
    'common.films': '本の映画',
    'common.or': 'または',
    'watchlist.empty': 'ウォッチリストは空です',
    'watchlist.emptyDescription': 'ブックマークアイコンをクリックして、後で見る映画を保存しましょう',
    'watchlist.browseFilms': '映画を探す',
    'watchlist.savedFilms': '本の映画を後で見る',
    'watchlist.savedFilm': '本の映画を後で見る',
    'watchlist.removeConfirm': 'ウォッチリストから削除しますか？',
    'watchlist.removeError': '削除に失敗しました。もう一度お試しください。',
    'watchlist.remove': 'リストから削除',
    // People page
    'people.discoverPeople': 'ユーザーを探す',
    'people.findConnect': '映画ファンを見つけてつながりましょう',
    'people.searchPlaceholder': 'ユーザー名または名前で検索...',
    'people.result': '件の結果',
    'people.results': '件の結果',
    'people.noUsersFound': 'ユーザーが見つかりません',
    'people.suggestedForYou': 'おすすめのユーザー',
    'people.noSuggestions': 'まだおすすめがありません',
    'people.noSuggestionsDescription': 'お気に入りの映画を追加して、パーソナライズされたおすすめを受け取りましょう',
    'people.followers': 'フォロワー',
    'people.films': '本の映画',
    'people.loading': '読み込み中...',
    'people.following': 'フォロー中',
    'people.follow': 'フォロー',
    'search.placeholder': '映画、監督、ムードを検索...',
    'search.results': '結果',
    'search.matches': '件の一致',
    'search.noResults': '該当するタイトルが見つかりません',
    'search.tryDifferent': '別の検索語をお試しください',
    'search.recent': '最近の検索',
    'search.trending': 'NEMAで人気',
    'home.independentCinema': 'インディペンデント映画',
    'home.tagline': '境界を超えた物語を発見。',
    'home.subtitle': '現代映画におけるユニークな声と視点のキュレーションコレクション。',
    'home.exploreFilms': '映画を探索',
    'home.featuredFilm': '注目の映画',
    'home.explore': '探索',
    'home.curatorsSelection': 'キュレーターズセレクション',
    'home.featured': '注目',
    'home.newReleases': '新作',
    'home.topRated': '高評価',
    'home.play': '再生',
    'home.moreInfo': '詳細情報',
    'home.supportCinema': 'インディペンデント映画を支援',
    'home.supportText': '映画製作者と映画愛好家のコミュニティに参加しましょう。私たちの時代を定義するユニークな物語を観て、共有し、発見しましょう。',
    'home.joinCommunity': 'コミュニティに参加',
    'home.allRightsReserved': '全著作権所有。',
    'catalog.filmCollection': '映画コレクション',
    'catalog.title': 'カタログ',
    'catalog.subtitle': 'アーカイブを閲覧して、次のお気に入り映画を見つけましょう。',
    'catalog.loadingMovies': '映画を読み込み中...',
    'catalog.loadingMore': 'さらに映画を読み込み中...',
    'catalog.showingAll': 'すべて表示',
    'catalog.noFilms': '条件に一致する映画が見つかりませんでした。',
    'catalog.category': 'カテゴリ',
    'catalog.year': '年',
    'catalog.language': '言語',
    'catalog.sort': '並び替え',
    'catalog.filters': 'フィルター',
    'catalog.newest': '新しい順',
    'catalog.oldest': '古い順',
    'catalog.aToZ': 'A-Z',
    'login.title': 'ログイン',
    'login.emailOrUsername': 'メールまたはユーザー名',
    'login.password': 'パスワード',
    'login.signingIn': 'ログイン中...',
    'login.signIn': 'ログイン',
    'login.noAccount': 'アカウントをお持ちでないですか？',
    'login.enterCredentials': 'メール/ユーザー名とパスワードを入力してください',
    'register.title': 'アカウント作成',
    'register.username': 'ユーザー名',
    'register.email': 'メール',
    'register.displayName': '表示名（任意）',
    'register.password': 'パスワード',
    'register.confirmPassword': 'パスワード確認',
    'register.creating': 'アカウント作成中...',
    'register.create': 'アカウント作成',
    'register.hasAccount': 'すでにアカウントをお持ちですか？',
    'contact.title': '連絡先',
    'contact.subtitle': 'チームにお問い合わせください',
    'contact.name': '名前',
    'contact.email': 'メール',
    'contact.message': 'メッセージ',
    'contact.send': 'メッセージを送信',
    'contact.sending': '送信中...',
    'about.title': '概要',
    'about.subtitle': 'NEMAについてもっと知る',
    'profile.title': 'プロフィール',
    'profile.editProfile': 'プロフィールを編集',
    'profile.followers': 'フォロワー',
    'profile.following': 'フォロー中',
    'profile.posts': '投稿',
    'video.play': '再生',
    'video.pause': '一時停止',
    'video.mute': 'ミュート',
    'video.unmute': 'ミュート解除',
    'video.fullscreen': 'フルスクリーン',
    'video.exitFullscreen': 'フルスクリーン終了',
    'video.synopsis': 'あらすじ',
    'video.genre': 'ジャンル',
    'video.language': '言語',
    'video.cast': 'キャスト',
    'video.more': '他',
    'video.relatedFilms': '関連作品',
    'video.addToWatchlist': 'リストに追加',
    'video.inWatchlist': 'リストに登録済み',
    'video.addToFavorites': 'お気に入りに追加',
    'video.inFavorites': 'お気に入り登録済み',
    'video.loading': '読み込み中...',
    'video.loadingMovie': '映画を読み込み中...',
    'video.noVideo': '動画がありません',
    'video.directedBy': '監督',
    'footer.films': '映画',
    'footer.about': '概要',
    'footer.contact': '連絡先',
    // Reviews
    'reviews.title': 'レビュー',
    'reviews.average': '平均',
    'reviews.clickToRate': 'クリックして評価',
    'reviews.nicknamePlaceholder': 'ニックネーム（任意）',
    'reviews.writeReview': '短いレビューを書く（任意）…',
    'reviews.submitReview': 'レビューを投稿',
    'reviews.updateReview': 'レビューを更新',
    'reviews.loading': 'レビューを読み込み中…',
    'reviews.noReviews': 'まだレビューはありません。',
    'reviews.deleteConfirm': 'レビューを削除してもよろしいですか？',
    'reviews.deleteError': '自分のレビューのみ削除できます',
    'reviews.rateLimitError': '試行回数が多すぎます。しばらくしてからお試しください。',
    'reviews.submitError': 'レビューの投稿に失敗しました。もう一度お試しください。',
    'reviews.deleteReviewError': 'レビューの削除に失敗しました。もう一度お試しください。',
    // Comments
    'comments.title': 'コメント',
    'comments.nicknamePlaceholder': 'ニックネーム（任意）',
    'comments.addComment': 'コメントを追加...',
    'comments.posting': '投稿中...',
    'comments.postComment': 'コメントを投稿',
    'comments.loading': 'コメントを読み込み中...',
    'comments.noComments': 'まだコメントはありません。最初のコメントを投稿しましょう！',
    'comments.delete': '削除',
    'comments.deleteConfirm': 'このコメントを削除してもよろしいですか？',
    'comments.deleteError': '自分のコメントのみ削除できます',
    'comments.rateLimitError': '削除試行回数が多すぎます。しばらくしてからお試しください。',
    'comments.postError': 'コメントの投稿に失敗しました',
    'comments.loadError': 'コメントの読み込みに失敗しました',
    'comments.deleteCommentError': 'コメントの削除に失敗しました',
  },
  ko: {
    'nav.home': '홈',
    'nav.about': '소개',
    'nav.catalog': '카탈로그',
    'nav.people': '사람들',
    'nav.contact': '연락처',
    'nav.settings': '설정',
    'nav.profile': '내 프로필',
    'nav.watchlist': '관심 목록',
    'nav.signOut': '로그아웃',
    'nav.signIn': '로그인',
    'nav.signUp': '회원가입',
    'settings.title': '설정',
    'settings.subtitle': '계정 설정 및 환경설정 관리',
    'settings.profile': '프로필',
    'settings.account': '계정',
    'settings.appearance': '모양',
    'settings.language': '언어',
    'settings.theme': '테마',
    'settings.save': '변경사항 저장',
    'settings.saving': '저장 중...',
    'settings.profileInfo': '프로필 정보',
    'settings.profilePicture': '프로필 사진',
    'settings.clickToUpload': '아바타를 클릭하여 새 이미지를 업로드하세요',
    'settings.bannerImage': '배너 이미지',
    'settings.recommendedSize': '권장 크기: 1500x500px',
    'settings.uploadBanner': '배너 업로드',
    'settings.uploading': '업로드 중...',
    'settings.displayName': '표시 이름',
    'settings.displayNamePlaceholder': '표시 이름',
    'settings.bio': '자기소개',
    'settings.bioPlaceholder': '자신에 대해 알려주세요...',
    'settings.accountInfo': '계정 정보',
    'settings.username': '사용자명',
    'settings.usernameCannotChange': '사용자명은 변경할 수 없습니다',
    'settings.email': '이메일',
    'settings.memberSince': '가입일',
    'settings.changePassword': '비밀번호 변경',
    'settings.currentPassword': '현재 비밀번호',
    'settings.currentPasswordPlaceholder': '현재 비밀번호 입력',
    'settings.newPassword': '새 비밀번호',
    'settings.newPasswordPlaceholder': '새 비밀번호 입력',
    'settings.confirmNewPassword': '새 비밀번호 확인',
    'settings.confirmPasswordPlaceholder': '새 비밀번호 확인',
    'settings.updatePassword': '비밀번호 업데이트',
    'settings.updating': '업데이트 중...',
    'settings.selectLanguage': '인터페이스에 사용할 언어를 선택하세요',
    'settings.languageAutoSave': '언어 변경은 자동으로 저장됩니다',
    'settings.someContentOriginal': '일부 콘텐츠는 원본 언어로 표시될 수 있습니다.',
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.seeAll': '모두 보기',
    'common.search': '검색',
    'common.clear': '지우기',
    'common.clearFilters': '필터 지우기',
    'common.films': '편의 영화',
    'common.or': '또는',
    'watchlist.empty': '관심목록이 비어 있습니다',
    'watchlist.emptyDescription': '북마크 아이콘을 클릭하여 나중에 볼 영화를 저장하세요',
    'watchlist.browseFilms': '영화 둘러보기',
    'watchlist.savedFilms': '편의 영화가 나중에 볼 목록에 저장됨',
    'watchlist.savedFilm': '편의 영화가 나중에 볼 목록에 저장됨',
    'watchlist.removeConfirm': '관심목록에서 삭제하시겠습니까?',
    'watchlist.removeError': '삭제에 실패했습니다. 다시 시도해 주세요.',
    'watchlist.remove': '목록에서 삭제',
    // People page
    'people.discoverPeople': '사람 찾기',
    'people.findConnect': '영화 애호가를 찾고 연결하세요',
    'people.searchPlaceholder': '사용자명 또는 이름으로 검색...',
    'people.result': '개 결과',
    'people.results': '개 결과',
    'people.noUsersFound': '사용자를 찾을 수 없습니다',
    'people.suggestedForYou': '추천 사용자',
    'people.noSuggestions': '아직 추천이 없습니다',
    'people.noSuggestionsDescription': '좋아하는 영화를 추가하여 맞춤 추천을 받아보세요',
    'people.followers': '팔로워',
    'people.films': '편의 영화',
    'people.loading': '로딩 중...',
    'people.following': '팔로잉',
    'people.follow': '팔로우',
    'search.placeholder': '영화, 감독, 분위기 검색...',
    'search.results': '결과',
    'search.matches': '개 일치',
    'search.noResults': '일치하는 제목이 없습니다',
    'search.tryDifferent': '다른 검색어를 시도해보세요',
    'search.recent': '최근 검색',
    'search.trending': 'NEMA에서 인기',
    'home.independentCinema': '독립 영화',
    'home.tagline': '경계를 넘는 이야기를 발견하세요.',
    'home.subtitle': '현대 영화에서 독특한 목소리와 관점의 큐레이션 컬렉션.',
    'home.exploreFilms': '영화 탐색',
    'home.featuredFilm': '추천 영화',
    'home.explore': '탐색',
    'home.curatorsSelection': '큐레이터 추천',
    'home.featured': '추천',
    'home.newReleases': '신작',
    'home.topRated': '최고 평점',
    'home.play': '재생',
    'home.moreInfo': '상세 정보',
    'home.supportCinema': '독립 영화 지원',
    'home.supportText': '영화 제작자와 영화 애호가의 커뮤니티에 참여하세요. 우리 시대를 정의하는 독특한 이야기를 보고, 공유하고, 발견하세요.',
    'home.joinCommunity': '커뮤니티 참여',
    'home.allRightsReserved': '모든 권리 보유.',
    'catalog.filmCollection': '영화 컬렉션',
    'catalog.title': '카탈로그',
    'catalog.subtitle': '아카이브를 탐색하고 다음 좋아하는 영화를 발견하세요.',
    'catalog.loadingMovies': '영화 로딩 중...',
    'catalog.loadingMore': '더 많은 영화 로딩 중...',
    'catalog.showingAll': '모두 표시',
    'catalog.noFilms': '기준에 맞는 영화를 찾을 수 없습니다.',
    'catalog.category': '카테고리',
    'catalog.year': '연도',
    'catalog.language': '언어',
    'catalog.sort': '정렬',
    'catalog.filters': '필터',
    'catalog.newest': '최신순',
    'catalog.oldest': '오래된순',
    'catalog.aToZ': 'A-Z',
    'login.title': '로그인',
    'login.emailOrUsername': '이메일 또는 사용자명',
    'login.password': '비밀번호',
    'login.signingIn': '로그인 중...',
    'login.signIn': '로그인',
    'login.noAccount': '계정이 없으신가요?',
    'login.enterCredentials': '이메일/사용자명과 비밀번호를 입력해주세요',
    'register.title': '계정 만들기',
    'register.username': '사용자명',
    'register.email': '이메일',
    'register.displayName': '표시 이름 (선택 사항)',
    'register.password': '비밀번호',
    'register.confirmPassword': '비밀번호 확인',
    'register.creating': '계정 생성 중...',
    'register.create': '계정 만들기',
    'register.hasAccount': '이미 계정이 있으신가요?',
    'contact.title': '연락처',
    'contact.subtitle': '팀에 연락하기',
    'contact.name': '이름',
    'contact.email': '이메일',
    'contact.message': '메시지',
    'contact.send': '메시지 보내기',
    'contact.sending': '보내는 중...',
    'about.title': '소개',
    'about.subtitle': 'NEMA에 대해 더 알아보기',
    'profile.title': '프로필',
    'profile.editProfile': '프로필 편집',
    'profile.followers': '팔로워',
    'profile.following': '팔로잉',
    'profile.posts': '게시물',
    'video.play': '재생',
    'video.pause': '일시정지',
    'video.mute': '음소거',
    'video.unmute': '음소거 해제',
    'video.fullscreen': '전체 화면',
    'video.exitFullscreen': '전체 화면 종료',
    'video.synopsis': '줄거리',
    'video.genre': '장르',
    'video.language': '언어',
    'video.cast': '출연진',
    'video.more': '더보기',
    'video.relatedFilms': '관련 영화',
    'video.addToWatchlist': '목록에 추가',
    'video.inWatchlist': '목록에 있음',
    'video.addToFavorites': '즐겨찾기에 추가',
    'video.inFavorites': '즐겨찾기됨',
    'video.loading': '로딩 중...',
    'video.loadingMovie': '영화 로딩 중...',
    'video.noVideo': '영상 없음',
    'video.directedBy': '감독',
    'footer.films': '영화',
    'footer.about': '소개',
    'footer.contact': '연락처',
    // Reviews
    'reviews.title': '리뷰',
    'reviews.average': '평균',
    'reviews.clickToRate': '클릭하여 평가',
    'reviews.nicknamePlaceholder': '닉네임 (선택 사항)',
    'reviews.writeReview': '짧은 리뷰를 작성하세요 (선택 사항)…',
    'reviews.submitReview': '리뷰 제출',
    'reviews.updateReview': '리뷰 업데이트',
    'reviews.loading': '리뷰 로딩 중…',
    'reviews.noReviews': '아직 리뷰가 없습니다.',
    'reviews.deleteConfirm': '리뷰를 삭제하시겠습니까?',
    'reviews.deleteError': '자신의 리뷰만 삭제할 수 있습니다',
    'reviews.rateLimitError': '너무 많은 시도입니다. 나중에 다시 시도해주세요.',
    'reviews.submitError': '리뷰 제출에 실패했습니다. 다시 시도해주세요.',
    'reviews.deleteReviewError': '리뷰 삭제에 실패했습니다. 다시 시도해주세요.',
    // Comments
    'comments.title': '댓글',
    'comments.nicknamePlaceholder': '닉네임 (선택 사항)',
    'comments.addComment': '댓글 추가...',
    'comments.posting': '게시 중...',
    'comments.postComment': '댓글 게시',
    'comments.loading': '댓글 로딩 중...',
    'comments.noComments': '아직 댓글이 없습니다. 첫 번째로 댓글을 달아보세요!',
    'comments.delete': '삭제',
    'comments.deleteConfirm': '이 댓글을 삭제하시겠습니까?',
    'comments.deleteError': '자신의 댓글만 삭제할 수 있습니다',
    'comments.rateLimitError': '삭제 시도가 너무 많습니다. 나중에 다시 시도해주세요.',
    'comments.postError': '댓글 게시에 실패했습니다',
    'comments.loadError': '댓글을 불러오는데 실패했습니다',
    'comments.deleteCommentError': '댓글 삭제에 실패했습니다',
  },
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.catalog': 'Catálogo',
    'nav.people': 'Pessoas',
    'nav.contact': 'Contato',
    'nav.settings': 'Configurações',
    'nav.profile': 'Meu Perfil',
    'nav.watchlist': 'Lista de interesse',
    'nav.signOut': 'Sair',
    'nav.signIn': 'Entrar',
    'nav.signUp': 'Cadastrar',
    'settings.title': 'Configurações',
    'settings.subtitle': 'Gerencie as configurações e preferências da sua conta',
    'settings.profile': 'Perfil',
    'settings.account': 'Conta',
    'settings.appearance': 'Aparência',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.save': 'Salvar alterações',
    'settings.saving': 'Salvando...',
    'settings.profileInfo': 'Informações do Perfil',
    'settings.profilePicture': 'Foto de Perfil',
    'settings.clickToUpload': 'Clique no avatar para enviar uma nova imagem',
    'settings.bannerImage': 'Imagem de Banner',
    'settings.recommendedSize': 'Tamanho recomendado: 1500x500px',
    'settings.uploadBanner': 'Enviar Banner',
    'settings.uploading': 'Enviando...',
    'settings.displayName': 'Nome de Exibição',
    'settings.displayNamePlaceholder': 'Seu nome de exibição',
    'settings.bio': 'Biografia',
    'settings.bioPlaceholder': 'Conte-nos sobre você...',
    'settings.accountInfo': 'Informações da Conta',
    'settings.username': 'Nome de usuário',
    'settings.usernameCannotChange': 'O nome de usuário não pode ser alterado',
    'settings.email': 'Email',
    'settings.memberSince': 'Membro desde',
    'settings.changePassword': 'Alterar Senha',
    'settings.currentPassword': 'Senha Atual',
    'settings.currentPasswordPlaceholder': 'Digite a senha atual',
    'settings.newPassword': 'Nova Senha',
    'settings.newPasswordPlaceholder': 'Digite a nova senha',
    'settings.confirmNewPassword': 'Confirmar Nova Senha',
    'settings.confirmPasswordPlaceholder': 'Confirme a nova senha',
    'settings.updatePassword': 'Atualizar Senha',
    'settings.updating': 'Atualizando...',
    'settings.selectLanguage': 'Selecione seu idioma preferido para a interface',
    'settings.languageAutoSave': 'Alterações de idioma são salvas automaticamente',
    'settings.someContentOriginal': 'Alguns conteúdos podem ainda aparecer no idioma original.',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.seeAll': 'Ver tudo',
    'common.search': 'Pesquisar',
    'common.clear': 'Limpar',
    'common.clearFilters': 'Limpar filtros',
    'common.films': 'filmes',
    'common.or': 'OU',
    'watchlist.empty': 'Sua lista está vazia',
    'watchlist.emptyDescription': 'Salve filmes para assistir mais tarde clicando no ícone de marcador',
    'watchlist.browseFilms': 'Explorar Filmes',
    'watchlist.savedFilms': 'filmes salvos para assistir mais tarde',
    'watchlist.savedFilm': 'filme salvo para assistir mais tarde',
    'watchlist.removeConfirm': 'Remover da sua lista?',
    'watchlist.removeError': 'Falha ao remover. Por favor, tente novamente.',
    'watchlist.remove': 'Remover da lista',
    // People page
    'people.discoverPeople': 'Descobrir Pessoas',
    'people.findConnect': 'Encontre e conecte-se com entusiastas do cinema',
    'people.searchPlaceholder': 'Pesquisar por nome de usuário ou nome...',
    'people.result': 'resultado',
    'people.results': 'resultados',
    'people.noUsersFound': 'Nenhum usuário encontrado',
    'people.suggestedForYou': 'Sugestões Para Você',
    'people.noSuggestions': 'Ainda sem sugestões',
    'people.noSuggestionsDescription': 'Adicione alguns filmes favoritos para receber recomendações personalizadas',
    'people.followers': 'seguidores',
    'people.films': 'filmes',
    'people.loading': 'Carregando...',
    'people.following': 'Seguindo',
    'people.follow': 'Seguir',
    'search.placeholder': 'Pesquisar filmes, diretores, gêneros...',
    'search.results': 'Resultados',
    'search.matches': 'correspondências',
    'search.noResults': 'Nenhum título encontrado para',
    'search.tryDifferent': 'Tente um termo de pesquisa diferente',
    'search.recent': 'Recentes',
    'search.trending': 'Em alta no NEMA',
    'home.independentCinema': 'Cinema Independente',
    'home.tagline': 'Descubra narrativas sem fronteiras.',
    'home.subtitle': 'Uma coleção curada de vozes e perspectivas únicas no cinema contemporâneo.',
    'home.exploreFilms': 'Explorar Filmes',
    'home.featuredFilm': 'Filme em Destaque',
    'home.explore': 'Explorar',
    'home.curatorsSelection': 'Seleção do Curador',
    'home.featured': 'Destaques',
    'home.newReleases': 'Novos Lançamentos',
    'home.topRated': 'Mais Bem Avaliados',
    'home.play': 'Reproduzir',
    'home.moreInfo': 'Mais Informações',
    'home.supportCinema': 'Apoie o Cinema Independente',
    'home.supportText': 'Junte-se à nossa comunidade de cineastas e entusiastas do cinema. Assista, compartilhe e descubra histórias únicas que definem nosso tempo.',
    'home.joinCommunity': 'Junte-se à Nossa Comunidade',
    'home.allRightsReserved': 'Todos os direitos reservados.',
    'catalog.filmCollection': 'Coleção de Filmes',
    'catalog.title': 'Catálogo',
    'catalog.subtitle': 'Navegue pelo arquivo e descubra seu próximo filme favorito.',
    'catalog.loadingMovies': 'Carregando filmes...',
    'catalog.loadingMore': 'Carregando mais filmes...',
    'catalog.showingAll': 'Mostrando todos os',
    'catalog.noFilms': 'Nenhum filme encontrado com esses critérios.',
    'catalog.category': 'Categoria',
    'catalog.year': 'Ano',
    'catalog.language': 'Idioma',
    'catalog.sort': 'Ordenar',
    'catalog.filters': 'Filtros',
    'catalog.newest': 'Mais recentes',
    'catalog.oldest': 'Mais antigos',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Entrar',
    'login.emailOrUsername': 'Email ou Nome de usuário',
    'login.password': 'Senha',
    'login.signingIn': 'ENTRANDO...',
    'login.signIn': 'ENTRAR',
    'login.noAccount': 'Não tem uma conta?',
    'login.enterCredentials': 'Por favor, insira seu email/nome de usuário e senha',
    'register.title': 'Criar Conta',
    'register.username': 'Nome de usuário',
    'register.email': 'Email',
    'register.displayName': 'Nome de exibição (opcional)',
    'register.password': 'Senha',
    'register.confirmPassword': 'Confirmar senha',
    'register.creating': 'CRIANDO CONTA...',
    'register.create': 'CRIAR CONTA',
    'register.hasAccount': 'Já tem uma conta?',
    'contact.title': 'Contato',
    'contact.subtitle': 'Entre em contato com nossa equipe',
    'contact.name': 'Nome',
    'contact.email': 'Email',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'about.title': 'Sobre',
    'about.subtitle': 'Saiba mais sobre o NEMA',
    'profile.title': 'Perfil',
    'profile.editProfile': 'Editar Perfil',
    'profile.followers': 'Seguidores',
    'profile.following': 'Seguindo',
    'profile.posts': 'Publicações',
    'video.play': 'Reproduzir',
    'video.pause': 'Pausar',
    'video.mute': 'Mudo',
    'video.unmute': 'Ativar som',
    'video.fullscreen': 'Tela cheia',
    'video.exitFullscreen': 'Sair da tela cheia',
    'video.synopsis': 'Sinopse',
    'video.genre': 'Gênero',
    'video.language': 'Idioma',
    'video.cast': 'Elenco',
    'video.more': 'mais',
    'video.relatedFilms': 'Filmes Relacionados',
    'video.addToWatchlist': 'Adicionar à Lista',
    'video.inWatchlist': 'Na Lista',
    'video.addToFavorites': 'Adicionar aos Favoritos',
    'video.inFavorites': 'Nos Favoritos',
    'video.loading': 'Carregando...',
    'video.loadingMovie': 'Carregando filme...',
    'video.noVideo': 'Nenhum vídeo disponível',
    'video.directedBy': 'Direção',
    'footer.films': 'Filmes',
    'footer.about': 'Sobre',
    'footer.contact': 'Contato',
    // Reviews
    'reviews.title': 'Avaliações',
    'reviews.average': 'média',
    'reviews.clickToRate': 'Clique para avaliar',
    'reviews.nicknamePlaceholder': 'Apelido (opcional)',
    'reviews.writeReview': 'Escreva uma avaliação curta (opcional)…',
    'reviews.submitReview': 'Enviar Avaliação',
    'reviews.updateReview': 'Atualizar Avaliação',
    'reviews.loading': 'Carregando avaliações…',
    'reviews.noReviews': 'Ainda não há avaliações.',
    'reviews.deleteConfirm': 'Tem certeza de que deseja excluir sua avaliação?',
    'reviews.deleteError': 'Você só pode excluir suas próprias avaliações',
    'reviews.rateLimitError': 'Muitas tentativas. Por favor, tente novamente mais tarde.',
    'reviews.submitError': 'Falha ao enviar avaliação. Por favor, tente novamente.',
    'reviews.deleteReviewError': 'Falha ao excluir avaliação. Por favor, tente novamente.',
    // Comments
    'comments.title': 'Comentários',
    'comments.nicknamePlaceholder': 'Apelido (opcional)',
    'comments.addComment': 'Adicionar um comentário...',
    'comments.posting': 'Publicando...',
    'comments.postComment': 'Publicar Comentário',
    'comments.loading': 'Carregando comentários...',
    'comments.noComments': 'Ainda não há comentários. Seja o primeiro a comentar!',
    'comments.delete': 'Excluir',
    'comments.deleteConfirm': 'Tem certeza de que deseja excluir este comentário?',
    'comments.deleteError': 'Você só pode excluir seus próprios comentários',
    'comments.rateLimitError': 'Muitas tentativas de exclusão. Por favor, tente novamente mais tarde.',
    'comments.postError': 'Falha ao publicar comentário',
    'comments.loadError': 'Falha ao carregar comentários',
    'comments.deleteCommentError': 'Falha ao excluir comentário',
  }
};

export const SettingsProvider = ({ children }) => {
  const [theme, setThemeState] = useState(() => {
    const saved = localStorage.getItem('theme');
    return saved && themes[saved] ? saved : 'dark';
  });

  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved && languages[saved] ? saved : 'en';
  });

  // Apply theme to document
  useEffect(() => {
    localStorage.setItem('theme', theme);
    document.documentElement.setAttribute('data-theme', theme);

    // Apply theme class to body
    const themeConfig = themes[theme];
    document.body.className = '';

    if (theme === 'light') {
      document.body.classList.add('light-theme');
    } else {
      document.body.classList.remove('light-theme');
    }
  }, [theme]);

  // Save language preference
  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setTheme = (newTheme) => {
    if (themes[newTheme]) {
      setThemeState(newTheme);
    }
  };

  const setLanguage = (newLanguage) => {
    if (languages[newLanguage]) {
      setLanguageState(newLanguage);
    }
  };

  // Translation function
  const t = (key) => {
    const langTranslations = translations[language] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  const value = {
    theme,
    setTheme,
    themes,
    currentTheme: themes[theme],
    language,
    setLanguage,
    languages,
    currentLanguage: languages[language],
    t
  };

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
};

export default SettingsContext;
