import React, { createContext, useContext, useState, useEffect } from 'react';

const SettingsContext = createContext(null);

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
};

// Available themes
export const themes = {
  dark: {
    id: 'dark',
    name: 'Dark',
    description: 'Default dark theme',
    colors: {
      background: 'bg-black',
      text: 'text-white',
      accent: 'amber'
    }
  },
  light: {
    id: 'light',
    name: 'Light',
    description: 'Light mode theme',
    colors: {
      background: 'bg-white',
      text: 'text-gray-900',
      accent: 'amber'
    }
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep blue dark theme',
    colors: {
      background: 'bg-slate-950',
      text: 'text-white',
      accent: 'blue'
    }
  },
  cinema: {
    id: 'cinema',
    name: 'Cinema',
    description: 'Classic cinema red accent',
    colors: {
      background: 'bg-neutral-950',
      text: 'text-white',
      accent: 'red'
    }
  }
};

// Available languages
export const languages = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸'
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸'
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷'
  },
  de: {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪'
  },
  zh: {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    flag: '🇨🇳'
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵'
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷'
  },
  pt: {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    flag: '🇧🇷'
  }
};

// Translation strings
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.catalog': 'Catalog',
    'nav.people': 'People',
    'nav.contact': 'Contact',
    'nav.settings': 'Settings',
    'nav.profile': 'My Profile',
    'nav.watchlist': 'Watchlist',
    'nav.signOut': 'Sign Out',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account settings and preferences',
    'settings.profile': 'Profile',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.seeAll': 'See all',
    'common.search': 'Search',
    'common.clear': 'Clear',
    'common.clearFilters': 'Clear Filters',
    'common.films': 'films',
    'common.or': 'OR',
    // Watchlist
    'watchlist.empty': 'Your watchlist is empty',
    'watchlist.emptyDescription': 'Save films to watch later by clicking the bookmark icon',
    'watchlist.browseFilms': 'Browse Films',
    // Search
    'search.placeholder': 'Search films, directors, moods...',
    'search.results': 'Results',
    'search.matches': 'matches',
    'search.noResults': 'No titles matched',
    'search.tryDifferent': 'Try a different search term',
    'search.recent': 'Recent',
    'search.trending': 'Trending on NEMA',
    // Home Page
    'home.independentCinema': 'Independent Cinema',
    'home.tagline': 'Discover storytelling beyond boundaries.',
    'home.subtitle': 'A curated collection of unique voices and perspectives in contemporary cinema.',
    'home.exploreFilms': 'Explore Films',
    'home.featuredFilm': 'Featured Film',
    'home.explore': 'Explore',
    'home.curatorsSelection': "Curator's Selection",
    'home.featured': 'Featured',
    'home.newReleases': 'New Releases',
    'home.topRated': 'Top Rated',
    'home.play': 'Play',
    'home.moreInfo': 'More Info',
    'home.supportCinema': 'Support Independent Cinema',
    'home.supportText': 'Join our community of filmmakers and film enthusiasts. Watch, share, and discover unique stories that define our time.',
    'home.joinCommunity': 'Join Our Community',
    'home.allRightsReserved': 'All rights reserved.',
    // Catalog Page
    'catalog.filmCollection': 'Film Collection',
    'catalog.title': 'Catalog',
    'catalog.subtitle': 'Browse the archive and discover your next favorite film.',
    'catalog.loadingMovies': 'Loading movies...',
    'catalog.loadingMore': 'Loading more films...',
    'catalog.showingAll': 'Showing all',
    'catalog.noFilms': 'No films found matching your criteria.',
    'catalog.category': 'Category',
    'catalog.year': 'Year',
    'catalog.language': 'Language',
    'catalog.sort': 'Sort',
    'catalog.filters': 'Filters',
    'catalog.newest': 'Newest',
    'catalog.oldest': 'Oldest',
    'catalog.aToZ': 'A-Z',
    // Login Page
    'login.title': 'Sign In',
    'login.emailOrUsername': 'Email or Username',
    'login.password': 'Password',
    'login.signingIn': 'SIGNING IN...',
    'login.signIn': 'SIGN IN',
    'login.noAccount': "Don't have an account?",
    'login.enterCredentials': 'Please enter your email/username and password',
    // Register Page
    'register.title': 'Create Account',
    'register.username': 'Username',
    'register.email': 'Email',
    'register.displayName': 'Display Name (optional)',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.creating': 'CREATING ACCOUNT...',
    'register.create': 'CREATE ACCOUNT',
    'register.hasAccount': 'Already have an account?',
    // Contact Page
    'contact.title': 'Contact',
    'contact.subtitle': 'Get in touch with our team',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    // About Page
    'about.title': 'About',
    'about.subtitle': 'Learn more about NEMA',
    // Profile Page
    'profile.title': 'Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.posts': 'Posts',
    // Video Player
    'video.play': 'Play',
    'video.pause': 'Pause',
    'video.mute': 'Mute',
    'video.unmute': 'Unmute',
    'video.fullscreen': 'Fullscreen',
    'video.exitFullscreen': 'Exit Fullscreen',
    // Footer
    'footer.films': 'Films',
    'footer.about': 'About',
    'footer.contact': 'Contact',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.catalog': 'Catálogo',
    'nav.people': 'Personas',
    'nav.contact': 'Contacto',
    'nav.settings': 'Configuración',
    'nav.profile': 'Mi Perfil',
    'nav.watchlist': 'Lista de seguimiento',
    'nav.signOut': 'Cerrar sesión',
    'nav.signIn': 'Iniciar sesión',
    'nav.signUp': 'Registrarse',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Administra la configuración y preferencias de tu cuenta',
    'settings.profile': 'Perfil',
    'settings.account': 'Cuenta',
    'settings.appearance': 'Apariencia',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.save': 'Guardar cambios',
    'settings.saving': 'Guardando...',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.seeAll': 'Ver todo',
    'common.search': 'Buscar',
    'common.clear': 'Limpiar',
    'common.clearFilters': 'Limpiar filtros',
    'common.films': 'películas',
    'watchlist.empty': 'Tu lista de seguimiento está vacía',
    'watchlist.emptyDescription': 'Guarda películas para ver más tarde haciendo clic en el icono de marcador',
    'watchlist.browseFilms': 'Explorar Películas',
    'common.or': 'O',
    'search.placeholder': 'Buscar películas, directores, géneros...',
    'search.results': 'Resultados',
    'search.matches': 'coincidencias',
    'search.noResults': 'No se encontraron títulos para',
    'search.tryDifferent': 'Intenta con otro término de búsqueda',
    'search.recent': 'Recientes',
    'search.trending': 'Tendencias en NEMA',
    'home.independentCinema': 'Cine Independiente',
    'home.tagline': 'Descubre narrativas sin fronteras.',
    'home.subtitle': 'Una colección curada de voces y perspectivas únicas en el cine contemporáneo.',
    'home.exploreFilms': 'Explorar Películas',
    'home.featuredFilm': 'Película Destacada',
    'home.explore': 'Explorar',
    'home.curatorsSelection': 'Selección del Curador',
    'home.featured': 'Destacados',
    'home.newReleases': 'Nuevos Lanzamientos',
    'home.topRated': 'Mejor Valorados',
    'home.play': 'Reproducir',
    'home.moreInfo': 'Más Información',
    'home.supportCinema': 'Apoya el Cine Independiente',
    'home.supportText': 'Únete a nuestra comunidad de cineastas y entusiastas del cine. Mira, comparte y descubre historias únicas que definen nuestro tiempo.',
    'home.joinCommunity': 'Únete a Nuestra Comunidad',
    'home.allRightsReserved': 'Todos los derechos reservados.',
    'catalog.filmCollection': 'Colección de Películas',
    'catalog.title': 'Catálogo',
    'catalog.subtitle': 'Explora el archivo y descubre tu próxima película favorita.',
    'catalog.loadingMovies': 'Cargando películas...',
    'catalog.loadingMore': 'Cargando más películas...',
    'catalog.showingAll': 'Mostrando todas',
    'catalog.noFilms': 'No se encontraron películas con esos criterios.',
    'catalog.category': 'Categoría',
    'catalog.year': 'Año',
    'catalog.language': 'Idioma',
    'catalog.sort': 'Ordenar',
    'catalog.filters': 'Filtros',
    'catalog.newest': 'Más recientes',
    'catalog.oldest': 'Más antiguos',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Iniciar Sesión',
    'login.emailOrUsername': 'Correo o Usuario',
    'login.password': 'Contraseña',
    'login.signingIn': 'INICIANDO SESIÓN...',
    'login.signIn': 'INICIAR SESIÓN',
    'login.noAccount': '¿No tienes cuenta?',
    'login.enterCredentials': 'Por favor ingresa tu correo/usuario y contraseña',
    'register.title': 'Crear Cuenta',
    'register.username': 'Usuario',
    'register.email': 'Correo',
    'register.displayName': 'Nombre para mostrar (opcional)',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar Contraseña',
    'register.creating': 'CREANDO CUENTA...',
    'register.create': 'CREAR CUENTA',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'contact.title': 'Contacto',
    'contact.subtitle': 'Ponte en contacto con nuestro equipo',
    'contact.name': 'Nombre',
    'contact.email': 'Correo',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'about.title': 'Acerca de',
    'about.subtitle': 'Conoce más sobre NEMA',
    'profile.title': 'Perfil',
    'profile.editProfile': 'Editar Perfil',
    'profile.followers': 'Seguidores',
    'profile.following': 'Siguiendo',
    'profile.posts': 'Publicaciones',
    'video.play': 'Reproducir',
    'video.pause': 'Pausar',
    'video.mute': 'Silenciar',
    'video.unmute': 'Activar sonido',
    'video.fullscreen': 'Pantalla completa',
    'video.exitFullscreen': 'Salir de pantalla completa',
    'footer.films': 'Películas',
    'footer.about': 'Acerca de',
    'footer.contact': 'Contacto',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.catalog': 'Catalogue',
    'nav.people': 'Personnes',
    'nav.contact': 'Contact',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Mon Profil',
    'nav.watchlist': 'Liste de suivi',
    'nav.signOut': 'Déconnexion',
    'nav.signIn': 'Connexion',
    'nav.signUp': "S'inscrire",
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez les paramètres et préférences de votre compte',
    'settings.profile': 'Profil',
    'settings.account': 'Compte',
    'settings.appearance': 'Apparence',
    'settings.language': 'Langue',
    'settings.theme': 'Thème',
    'settings.save': 'Enregistrer',
    'settings.saving': 'Enregistrement...',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.seeAll': 'Voir tout',
    'common.search': 'Rechercher',
    'common.clear': 'Effacer',
    'common.clearFilters': 'Effacer les filtres',
    'common.films': 'films',
    'common.or': 'OU',
    'watchlist.empty': 'Votre liste est vide',
    'watchlist.emptyDescription': 'Enregistrez des films à regarder plus tard en cliquant sur l\'icône de signet',
    'watchlist.browseFilms': 'Parcourir les Films',
    'search.placeholder': 'Rechercher films, réalisateurs, ambiances...',
    'search.results': 'Résultats',
    'search.matches': 'correspondances',
    'search.noResults': 'Aucun titre trouvé pour',
    'search.tryDifferent': 'Essayez un autre terme de recherche',
    'search.recent': 'Récents',
    'search.trending': 'Tendances sur NEMA',
    'home.independentCinema': 'Cinéma Indépendant',
    'home.tagline': 'Découvrez des récits sans frontières.',
    'home.subtitle': 'Une collection de voix et perspectives uniques dans le cinéma contemporain.',
    'home.exploreFilms': 'Explorer les Films',
    'home.featuredFilm': 'Film en Vedette',
    'home.explore': 'Explorer',
    'home.curatorsSelection': 'Sélection du Curateur',
    'home.featured': 'En Vedette',
    'home.newReleases': 'Nouvelles Sorties',
    'home.topRated': 'Les Mieux Notés',
    'home.play': 'Lecture',
    'home.moreInfo': 'Plus d\'Infos',
    'home.supportCinema': 'Soutenez le Cinéma Indépendant',
    'home.supportText': 'Rejoignez notre communauté de cinéastes et passionnés. Regardez, partagez et découvrez des histoires uniques qui définissent notre époque.',
    'home.joinCommunity': 'Rejoindre Notre Communauté',
    'home.allRightsReserved': 'Tous droits réservés.',
    'catalog.filmCollection': 'Collection de Films',
    'catalog.title': 'Catalogue',
    'catalog.subtitle': 'Parcourez les archives et découvrez votre prochain film préféré.',
    'catalog.loadingMovies': 'Chargement des films...',
    'catalog.loadingMore': 'Chargement de plus de films...',
    'catalog.showingAll': 'Affichage de tous les',
    'catalog.noFilms': 'Aucun film trouvé correspondant à vos critères.',
    'catalog.category': 'Catégorie',
    'catalog.year': 'Année',
    'catalog.language': 'Langue',
    'catalog.sort': 'Trier',
    'catalog.filters': 'Filtres',
    'catalog.newest': 'Plus récents',
    'catalog.oldest': 'Plus anciens',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Connexion',
    'login.emailOrUsername': 'Email ou Nom d\'utilisateur',
    'login.password': 'Mot de passe',
    'login.signingIn': 'CONNEXION...',
    'login.signIn': 'SE CONNECTER',
    'login.noAccount': 'Pas de compte?',
    'login.enterCredentials': 'Veuillez entrer votre email/nom d\'utilisateur et mot de passe',
    'register.title': 'Créer un Compte',
    'register.username': 'Nom d\'utilisateur',
    'register.email': 'Email',
    'register.displayName': 'Nom d\'affichage (facultatif)',
    'register.password': 'Mot de passe',
    'register.confirmPassword': 'Confirmer le mot de passe',
    'register.creating': 'CRÉATION DU COMPTE...',
    'register.create': 'CRÉER UN COMPTE',
    'register.hasAccount': 'Déjà un compte?',
    'contact.title': 'Contact',
    'contact.subtitle': 'Contactez notre équipe',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le Message',
    'contact.sending': 'Envoi...',
    'about.title': 'À propos',
    'about.subtitle': 'En savoir plus sur NEMA',
    'profile.title': 'Profil',
    'profile.editProfile': 'Modifier le Profil',
    'profile.followers': 'Abonnés',
    'profile.following': 'Abonnements',
    'profile.posts': 'Publications',
    'video.play': 'Lecture',
    'video.pause': 'Pause',
    'video.mute': 'Couper le son',
    'video.unmute': 'Activer le son',
    'video.fullscreen': 'Plein écran',
    'video.exitFullscreen': 'Quitter le plein écran',
    'footer.films': 'Films',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.catalog': 'Katalog',
    'nav.people': 'Personen',
    'nav.contact': 'Kontakt',
    'nav.settings': 'Einstellungen',
    'nav.profile': 'Mein Profil',
    'nav.watchlist': 'Merkliste',
    'nav.signOut': 'Abmelden',
    'nav.signIn': 'Anmelden',
    'nav.signUp': 'Registrieren',
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Verwalten Sie Ihre Kontoeinstellungen und Präferenzen',
    'settings.profile': 'Profil',
    'settings.account': 'Konto',
    'settings.appearance': 'Erscheinungsbild',
    'settings.language': 'Sprache',
    'settings.theme': 'Thema',
    'settings.save': 'Änderungen speichern',
    'settings.saving': 'Speichern...',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.seeAll': 'Alle anzeigen',
    'common.search': 'Suchen',
    'common.clear': 'Löschen',
    'common.clearFilters': 'Filter löschen',
    'common.films': 'Filme',
    'common.or': 'ODER',
    'watchlist.empty': 'Ihre Merkliste ist leer',
    'watchlist.emptyDescription': 'Speichern Sie Filme zum späteren Ansehen, indem Sie auf das Lesezeichen-Symbol klicken',
    'watchlist.browseFilms': 'Filme durchsuchen',
    'search.placeholder': 'Filme, Regisseure, Stimmungen suchen...',
    'search.results': 'Ergebnisse',
    'search.matches': 'Treffer',
    'search.noResults': 'Keine Titel gefunden für',
    'search.tryDifferent': 'Versuchen Sie einen anderen Suchbegriff',
    'search.recent': 'Zuletzt gesucht',
    'search.trending': 'Beliebt auf NEMA',
    'home.independentCinema': 'Unabhängiges Kino',
    'home.tagline': 'Entdecken Sie Geschichten ohne Grenzen.',
    'home.subtitle': 'Eine kuratierte Sammlung einzigartiger Stimmen und Perspektiven im zeitgenössischen Kino.',
    'home.exploreFilms': 'Filme Entdecken',
    'home.featuredFilm': 'Ausgewählter Film',
    'home.explore': 'Entdecken',
    'home.curatorsSelection': 'Kurator-Auswahl',
    'home.featured': 'Ausgewählt',
    'home.newReleases': 'Neuerscheinungen',
    'home.topRated': 'Bestbewertet',
    'home.play': 'Abspielen',
    'home.moreInfo': 'Mehr Infos',
    'home.supportCinema': 'Unterstützen Sie Unabhängiges Kino',
    'home.supportText': 'Treten Sie unserer Gemeinschaft von Filmemachern und Filmliebhabern bei. Schauen, teilen und entdecken Sie einzigartige Geschichten, die unsere Zeit definieren.',
    'home.joinCommunity': 'Unserer Gemeinschaft Beitreten',
    'home.allRightsReserved': 'Alle Rechte vorbehalten.',
    'catalog.filmCollection': 'Filmsammlung',
    'catalog.title': 'Katalog',
    'catalog.subtitle': 'Durchsuchen Sie das Archiv und entdecken Sie Ihren nächsten Lieblingsfilm.',
    'catalog.loadingMovies': 'Filme werden geladen...',
    'catalog.loadingMore': 'Weitere Filme werden geladen...',
    'catalog.showingAll': 'Zeige alle',
    'catalog.noFilms': 'Keine Filme gefunden, die Ihren Kriterien entsprechen.',
    'catalog.category': 'Kategorie',
    'catalog.year': 'Jahr',
    'catalog.language': 'Sprache',
    'catalog.sort': 'Sortieren',
    'catalog.filters': 'Filter',
    'catalog.newest': 'Neueste',
    'catalog.oldest': 'Älteste',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Anmelden',
    'login.emailOrUsername': 'E-Mail oder Benutzername',
    'login.password': 'Passwort',
    'login.signingIn': 'ANMELDEN...',
    'login.signIn': 'ANMELDEN',
    'login.noAccount': 'Noch kein Konto?',
    'login.enterCredentials': 'Bitte geben Sie Ihre E-Mail/Benutzername und Passwort ein',
    'register.title': 'Konto Erstellen',
    'register.username': 'Benutzername',
    'register.email': 'E-Mail',
    'register.displayName': 'Anzeigename (optional)',
    'register.password': 'Passwort',
    'register.confirmPassword': 'Passwort bestätigen',
    'register.creating': 'KONTO WIRD ERSTELLT...',
    'register.create': 'KONTO ERSTELLEN',
    'register.hasAccount': 'Bereits ein Konto?',
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Kontaktieren Sie unser Team',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht Senden',
    'contact.sending': 'Senden...',
    'about.title': 'Über uns',
    'about.subtitle': 'Erfahren Sie mehr über NEMA',
    'profile.title': 'Profil',
    'profile.editProfile': 'Profil Bearbeiten',
    'profile.followers': 'Follower',
    'profile.following': 'Folge ich',
    'profile.posts': 'Beiträge',
    'video.play': 'Abspielen',
    'video.pause': 'Pause',
    'video.mute': 'Stumm',
    'video.unmute': 'Ton an',
    'video.fullscreen': 'Vollbild',
    'video.exitFullscreen': 'Vollbild beenden',
    'footer.films': 'Filme',
    'footer.about': 'Über uns',
    'footer.contact': 'Kontakt',
  },
  zh: {
    'nav.home': '首页',
    'nav.about': '关于',
    'nav.catalog': '目录',
    'nav.people': '用户',
    'nav.contact': '联系',
    'nav.settings': '设置',
    'nav.profile': '我的资料',
    'nav.watchlist': '观看列表',
    'nav.signOut': '退出',
    'nav.signIn': '登录',
    'nav.signUp': '注册',
    'settings.title': '设置',
    'settings.subtitle': '管理您的账户设置和偏好',
    'settings.profile': '个人资料',
    'settings.account': '账户',
    'settings.appearance': '外观',
    'settings.language': '语言',
    'settings.theme': '主题',
    'settings.save': '保存更改',
    'settings.saving': '保存中...',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.seeAll': '查看全部',
    'common.search': '搜索',
    'common.clear': '清除',
    'common.clearFilters': '清除筛选',
    'common.films': '部电影',
    'common.or': '或',
    'watchlist.empty': '您的观看列表为空',
    'watchlist.emptyDescription': '点击书签图标保存稍后观看的电影',
    'watchlist.browseFilms': '浏览电影',
    'search.placeholder': '搜索电影、导演、风格...',
    'search.results': '结果',
    'search.matches': '个匹配',
    'search.noResults': '未找到相关标题',
    'search.tryDifferent': '请尝试其他搜索词',
    'search.recent': '最近搜索',
    'search.trending': 'NEMA热门',
    'home.independentCinema': '独立电影',
    'home.tagline': '发现无边界的故事。',
    'home.subtitle': '当代电影中独特声音和视角的精选合集。',
    'home.exploreFilms': '探索电影',
    'home.featuredFilm': '精选电影',
    'home.explore': '探索',
    'home.curatorsSelection': '策展人精选',
    'home.featured': '精选',
    'home.newReleases': '新片上映',
    'home.topRated': '最高评分',
    'home.play': '播放',
    'home.moreInfo': '更多信息',
    'home.supportCinema': '支持独立电影',
    'home.supportText': '加入我们的电影制作人和电影爱好者社区。观看、分享和发现定义我们时代的独特故事。',
    'home.joinCommunity': '加入我们的社区',
    'home.allRightsReserved': '版权所有。',
    'catalog.filmCollection': '电影合集',
    'catalog.title': '目录',
    'catalog.subtitle': '浏览档案，发现您的下一部最爱电影。',
    'catalog.loadingMovies': '正在加载电影...',
    'catalog.loadingMore': '正在加载更多电影...',
    'catalog.showingAll': '显示全部',
    'catalog.noFilms': '未找到符合条件的电影。',
    'catalog.category': '类别',
    'catalog.year': '年份',
    'catalog.language': '语言',
    'catalog.sort': '排序',
    'catalog.filters': '筛选',
    'catalog.newest': '最新',
    'catalog.oldest': '最早',
    'catalog.aToZ': 'A-Z',
    'login.title': '登录',
    'login.emailOrUsername': '邮箱或用户名',
    'login.password': '密码',
    'login.signingIn': '登录中...',
    'login.signIn': '登录',
    'login.noAccount': '还没有账户？',
    'login.enterCredentials': '请输入您的邮箱/用户名和密码',
    'register.title': '创建账户',
    'register.username': '用户名',
    'register.email': '邮箱',
    'register.displayName': '显示名称（可选）',
    'register.password': '密码',
    'register.confirmPassword': '确认密码',
    'register.creating': '创建账户中...',
    'register.create': '创建账户',
    'register.hasAccount': '已有账户？',
    'contact.title': '联系',
    'contact.subtitle': '与我们的团队联系',
    'contact.name': '姓名',
    'contact.email': '邮箱',
    'contact.message': '消息',
    'contact.send': '发送消息',
    'contact.sending': '发送中...',
    'about.title': '关于',
    'about.subtitle': '了解更多关于NEMA',
    'profile.title': '个人资料',
    'profile.editProfile': '编辑资料',
    'profile.followers': '粉丝',
    'profile.following': '关注',
    'profile.posts': '帖子',
    'video.play': '播放',
    'video.pause': '暂停',
    'video.mute': '静音',
    'video.unmute': '取消静音',
    'video.fullscreen': '全屏',
    'video.exitFullscreen': '退出全屏',
    'footer.films': '电影',
    'footer.about': '关于',
    'footer.contact': '联系',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.about': '概要',
    'nav.catalog': 'カタログ',
    'nav.people': 'ユーザー',
    'nav.contact': '連絡先',
    'nav.settings': '設定',
    'nav.profile': 'マイプロフィール',
    'nav.watchlist': 'ウォッチリスト',
    'nav.signOut': 'ログアウト',
    'nav.signIn': 'ログイン',
    'nav.signUp': '新規登録',
    'settings.title': '設定',
    'settings.subtitle': 'アカウント設定と環境設定を管理',
    'settings.profile': 'プロフィール',
    'settings.account': 'アカウント',
    'settings.appearance': '外観',
    'settings.language': '言語',
    'settings.theme': 'テーマ',
    'settings.save': '変更を保存',
    'settings.saving': '保存中...',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.seeAll': 'すべて見る',
    'common.search': '検索',
    'common.clear': 'クリア',
    'common.clearFilters': 'フィルターをクリア',
    'common.films': '本の映画',
    'common.or': 'または',
    'watchlist.empty': 'ウォッチリストは空です',
    'watchlist.emptyDescription': 'ブックマークアイコンをクリックして、後で見る映画を保存しましょう',
    'watchlist.browseFilms': '映画を探す',
    'search.placeholder': '映画、監督、ムードを検索...',
    'search.results': '結果',
    'search.matches': '件の一致',
    'search.noResults': '該当するタイトルが見つかりません',
    'search.tryDifferent': '別の検索語をお試しください',
    'search.recent': '最近の検索',
    'search.trending': 'NEMAで人気',
    'home.independentCinema': 'インディペンデント映画',
    'home.tagline': '境界を超えた物語を発見。',
    'home.subtitle': '現代映画におけるユニークな声と視点のキュレーションコレクション。',
    'home.exploreFilms': '映画を探索',
    'home.featuredFilm': '注目の映画',
    'home.explore': '探索',
    'home.curatorsSelection': 'キュレーターズセレクション',
    'home.featured': '注目',
    'home.newReleases': '新作',
    'home.topRated': '高評価',
    'home.play': '再生',
    'home.moreInfo': '詳細情報',
    'home.supportCinema': 'インディペンデント映画を支援',
    'home.supportText': '映画製作者と映画愛好家のコミュニティに参加しましょう。私たちの時代を定義するユニークな物語を観て、共有し、発見しましょう。',
    'home.joinCommunity': 'コミュニティに参加',
    'home.allRightsReserved': '全著作権所有。',
    'catalog.filmCollection': '映画コレクション',
    'catalog.title': 'カタログ',
    'catalog.subtitle': 'アーカイブを閲覧して、次のお気に入り映画を見つけましょう。',
    'catalog.loadingMovies': '映画を読み込み中...',
    'catalog.loadingMore': 'さらに映画を読み込み中...',
    'catalog.showingAll': 'すべて表示',
    'catalog.noFilms': '条件に一致する映画が見つかりませんでした。',
    'catalog.category': 'カテゴリ',
    'catalog.year': '年',
    'catalog.language': '言語',
    'catalog.sort': '並び替え',
    'catalog.filters': 'フィルター',
    'catalog.newest': '新しい順',
    'catalog.oldest': '古い順',
    'catalog.aToZ': 'A-Z',
    'login.title': 'ログイン',
    'login.emailOrUsername': 'メールまたはユーザー名',
    'login.password': 'パスワード',
    'login.signingIn': 'ログイン中...',
    'login.signIn': 'ログイン',
    'login.noAccount': 'アカウントをお持ちでないですか？',
    'login.enterCredentials': 'メール/ユーザー名とパスワードを入力してください',
    'register.title': 'アカウント作成',
    'register.username': 'ユーザー名',
    'register.email': 'メール',
    'register.displayName': '表示名（任意）',
    'register.password': 'パスワード',
    'register.confirmPassword': 'パスワード確認',
    'register.creating': 'アカウント作成中...',
    'register.create': 'アカウント作成',
    'register.hasAccount': 'すでにアカウントをお持ちですか？',
    'contact.title': '連絡先',
    'contact.subtitle': 'チームにお問い合わせください',
    'contact.name': '名前',
    'contact.email': 'メール',
    'contact.message': 'メッセージ',
    'contact.send': 'メッセージを送信',
    'contact.sending': '送信中...',
    'about.title': '概要',
    'about.subtitle': 'NEMAについてもっと知る',
    'profile.title': 'プロフィール',
    'profile.editProfile': 'プロフィールを編集',
    'profile.followers': 'フォロワー',
    'profile.following': 'フォロー中',
    'profile.posts': '投稿',
    'video.play': '再生',
    'video.pause': '一時停止',
    'video.mute': 'ミュート',
    'video.unmute': 'ミュート解除',
    'video.fullscreen': 'フルスクリーン',
    'video.exitFullscreen': 'フルスクリーン終了',
    'footer.films': '映画',
    'footer.about': '概要',
    'footer.contact': '連絡先',
  },
  ko: {
    'nav.home': '홈',
    'nav.about': '소개',
    'nav.catalog': '카탈로그',
    'nav.people': '사람들',
    'nav.contact': '연락처',
    'nav.settings': '설정',
    'nav.profile': '내 프로필',
    'nav.watchlist': '관심 목록',
    'nav.signOut': '로그아웃',
    'nav.signIn': '로그인',
    'nav.signUp': '회원가입',
    'settings.title': '설정',
    'settings.subtitle': '계정 설정 및 환경설정 관리',
    'settings.profile': '프로필',
    'settings.account': '계정',
    'settings.appearance': '모양',
    'settings.language': '언어',
    'settings.theme': '테마',
    'settings.save': '변경사항 저장',
    'settings.saving': '저장 중...',
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.seeAll': '모두 보기',
    'common.search': '검색',
    'common.clear': '지우기',
    'common.clearFilters': '필터 지우기',
    'common.films': '편의 영화',
    'common.or': '또는',
    'watchlist.empty': '관심목록이 비어 있습니다',
    'watchlist.emptyDescription': '북마크 아이콘을 클릭하여 나중에 볼 영화를 저장하세요',
    'watchlist.browseFilms': '영화 둘러보기',
    'search.placeholder': '영화, 감독, 분위기 검색...',
    'search.results': '결과',
    'search.matches': '개 일치',
    'search.noResults': '일치하는 제목이 없습니다',
    'search.tryDifferent': '다른 검색어를 시도해보세요',
    'search.recent': '최근 검색',
    'search.trending': 'NEMA에서 인기',
    'home.independentCinema': '독립 영화',
    'home.tagline': '경계를 넘는 이야기를 발견하세요.',
    'home.subtitle': '현대 영화에서 독특한 목소리와 관점의 큐레이션 컬렉션.',
    'home.exploreFilms': '영화 탐색',
    'home.featuredFilm': '추천 영화',
    'home.explore': '탐색',
    'home.curatorsSelection': '큐레이터 추천',
    'home.featured': '추천',
    'home.newReleases': '신작',
    'home.topRated': '최고 평점',
    'home.play': '재생',
    'home.moreInfo': '상세 정보',
    'home.supportCinema': '독립 영화 지원',
    'home.supportText': '영화 제작자와 영화 애호가의 커뮤니티에 참여하세요. 우리 시대를 정의하는 독특한 이야기를 보고, 공유하고, 발견하세요.',
    'home.joinCommunity': '커뮤니티 참여',
    'home.allRightsReserved': '모든 권리 보유.',
    'catalog.filmCollection': '영화 컬렉션',
    'catalog.title': '카탈로그',
    'catalog.subtitle': '아카이브를 탐색하고 다음 좋아하는 영화를 발견하세요.',
    'catalog.loadingMovies': '영화 로딩 중...',
    'catalog.loadingMore': '더 많은 영화 로딩 중...',
    'catalog.showingAll': '모두 표시',
    'catalog.noFilms': '기준에 맞는 영화를 찾을 수 없습니다.',
    'catalog.category': '카테고리',
    'catalog.year': '연도',
    'catalog.language': '언어',
    'catalog.sort': '정렬',
    'catalog.filters': '필터',
    'catalog.newest': '최신순',
    'catalog.oldest': '오래된순',
    'catalog.aToZ': 'A-Z',
    'login.title': '로그인',
    'login.emailOrUsername': '이메일 또는 사용자명',
    'login.password': '비밀번호',
    'login.signingIn': '로그인 중...',
    'login.signIn': '로그인',
    'login.noAccount': '계정이 없으신가요?',
    'login.enterCredentials': '이메일/사용자명과 비밀번호를 입력해주세요',
    'register.title': '계정 만들기',
    'register.username': '사용자명',
    'register.email': '이메일',
    'register.displayName': '표시 이름 (선택 사항)',
    'register.password': '비밀번호',
    'register.confirmPassword': '비밀번호 확인',
    'register.creating': '계정 생성 중...',
    'register.create': '계정 만들기',
    'register.hasAccount': '이미 계정이 있으신가요?',
    'contact.title': '연락처',
    'contact.subtitle': '팀에 연락하기',
    'contact.name': '이름',
    'contact.email': '이메일',
    'contact.message': '메시지',
    'contact.send': '메시지 보내기',
    'contact.sending': '보내는 중...',
    'about.title': '소개',
    'about.subtitle': 'NEMA에 대해 더 알아보기',
    'profile.title': '프로필',
    'profile.editProfile': '프로필 편집',
    'profile.followers': '팔로워',
    'profile.following': '팔로잉',
    'profile.posts': '게시물',
    'video.play': '재생',
    'video.pause': '일시정지',
    'video.mute': '음소거',
    'video.unmute': '음소거 해제',
    'video.fullscreen': '전체 화면',
    'video.exitFullscreen': '전체 화면 종료',
    'footer.films': '영화',
    'footer.about': '소개',
    'footer.contact': '연락처',
  },
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.catalog': 'Catálogo',
    'nav.people': 'Pessoas',
    'nav.contact': 'Contato',
    'nav.settings': 'Configurações',
    'nav.profile': 'Meu Perfil',
    'nav.watchlist': 'Lista de interesse',
    'nav.signOut': 'Sair',
    'nav.signIn': 'Entrar',
    'nav.signUp': 'Cadastrar',
    'settings.title': 'Configurações',
    'settings.subtitle': 'Gerencie as configurações e preferências da sua conta',
    'settings.profile': 'Perfil',
    'settings.account': 'Conta',
    'settings.appearance': 'Aparência',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.save': 'Salvar alterações',
    'settings.saving': 'Salvando...',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.seeAll': 'Ver tudo',
    'common.search': 'Pesquisar',
    'common.clear': 'Limpar',
    'common.clearFilters': 'Limpar filtros',
    'common.films': 'filmes',
    'common.or': 'OU',
    'watchlist.empty': 'Sua lista está vazia',
    'watchlist.emptyDescription': 'Salve filmes para assistir mais tarde clicando no ícone de marcador',
    'watchlist.browseFilms': 'Explorar Filmes',
    'search.placeholder': 'Pesquisar filmes, diretores, gêneros...',
    'search.results': 'Resultados',
    'search.matches': 'correspondências',
    'search.noResults': 'Nenhum título encontrado para',
    'search.tryDifferent': 'Tente um termo de pesquisa diferente',
    'search.recent': 'Recentes',
    'search.trending': 'Em alta no NEMA',
    'home.independentCinema': 'Cinema Independente',
    'home.tagline': 'Descubra narrativas sem fronteiras.',
    'home.subtitle': 'Uma coleção curada de vozes e perspectivas únicas no cinema contemporâneo.',
    'home.exploreFilms': 'Explorar Filmes',
    'home.featuredFilm': 'Filme em Destaque',
    'home.explore': 'Explorar',
    'home.curatorsSelection': 'Seleção do Curador',
    'home.featured': 'Destaques',
    'home.newReleases': 'Novos Lançamentos',
    'home.topRated': 'Mais Bem Avaliados',
    'home.play': 'Reproduzir',
    'home.moreInfo': 'Mais Informações',
    'home.supportCinema': 'Apoie o Cinema Independente',
    'home.supportText': 'Junte-se à nossa comunidade de cineastas e entusiastas do cinema. Assista, compartilhe e descubra histórias únicas que definem nosso tempo.',
    'home.joinCommunity': 'Junte-se à Nossa Comunidade',
    'home.allRightsReserved': 'Todos os direitos reservados.',
    'catalog.filmCollection': 'Coleção de Filmes',
    'catalog.title': 'Catálogo',
    'catalog.subtitle': 'Navegue pelo arquivo e descubra seu próximo filme favorito.',
    'catalog.loadingMovies': 'Carregando filmes...',
    'catalog.loadingMore': 'Carregando mais filmes...',
    'catalog.showingAll': 'Mostrando todos os',
    'catalog.noFilms': 'Nenhum filme encontrado com esses critérios.',
    'catalog.category': 'Categoria',
    'catalog.year': 'Ano',
    'catalog.language': 'Idioma',
    'catalog.sort': 'Ordenar',
    'catalog.filters': 'Filtros',
    'catalog.newest': 'Mais recentes',
    'catalog.oldest': 'Mais antigos',
    'catalog.aToZ': 'A-Z',
    'login.title': 'Entrar',
    'login.emailOrUsername': 'Email ou Nome de usuário',
    'login.password': 'Senha',
    'login.signingIn': 'ENTRANDO...',
    'login.signIn': 'ENTRAR',
    'login.noAccount': 'Não tem uma conta?',
    'login.enterCredentials': 'Por favor, insira seu email/nome de usuário e senha',
    'register.title': 'Criar Conta',
    'register.username': 'Nome de usuário',
    'register.email': 'Email',
    'register.displayName': 'Nome de exibição (opcional)',
    'register.password': 'Senha',
    'register.confirmPassword': 'Confirmar senha',
    'register.creating': 'CRIANDO CONTA...',
    'register.create': 'CRIAR CONTA',
    'register.hasAccount': 'Já tem uma conta?',
    'contact.title': 'Contato',
    'contact.subtitle': 'Entre em contato com nossa equipe',
    'contact.name': 'Nome',
    'contact.email': 'Email',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'about.title': 'Sobre',
    'about.subtitle': 'Saiba mais sobre o NEMA',
    'profile.title': 'Perfil',
    'profile.editProfile': 'Editar Perfil',
    'profile.followers': 'Seguidores',
    'profile.following': 'Seguindo',
    'profile.posts': 'Publicações',
    'video.play': 'Reproduzir',
    'video.pause': 'Pausar',
    'video.mute': 'Mudo',
    'video.unmute': 'Ativar som',
    'video.fullscreen': 'Tela cheia',
    'video.exitFullscreen': 'Sair da tela cheia',
    'footer.films': 'Filmes',
    'footer.about': 'Sobre',
    'footer.contact': 'Contato',
  }
};

export const SettingsProvider = ({ children }) => {
  const [theme, setThemeState] = useState(() => {
    const saved = localStorage.getItem('theme');
    return saved && themes[saved] ? saved : 'dark';
  });

  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved && languages[saved] ? saved : 'en';
  });

  // Apply theme to document
  useEffect(() => {
    localStorage.setItem('theme', theme);
    document.documentElement.setAttribute('data-theme', theme);

    // Apply theme class to body
    const themeConfig = themes[theme];
    document.body.className = '';

    if (theme === 'light') {
      document.body.classList.add('light-theme');
    } else {
      document.body.classList.remove('light-theme');
    }
  }, [theme]);

  // Save language preference
  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setTheme = (newTheme) => {
    if (themes[newTheme]) {
      setThemeState(newTheme);
    }
  };

  const setLanguage = (newLanguage) => {
    if (languages[newLanguage]) {
      setLanguageState(newLanguage);
    }
  };

  // Translation function
  const t = (key) => {
    const langTranslations = translations[language] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  const value = {
    theme,
    setTheme,
    themes,
    currentTheme: themes[theme],
    language,
    setLanguage,
    languages,
    currentLanguage: languages[language],
    t
  };

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
};

export default SettingsContext;
